In [841]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
from scipy.stats.mstats import winsorize

import warnings
warnings.filterwarnings("ignore")
warnings.warn("this will not show")

%matplotlib inline
# %matplotlib notebook

plt.rcParams["figure.figsize"] = (10, 6)
# plt.rcParams['figure.dpi'] = 100

sns.set_style("whitegrid")
pd.set_option('display.float_format', lambda x: '%.3f' % x)


In [842]:
df0 = pd.read_csv("autoscout_cleaned.csv")
df = df0.copy()
df.head(3).T


0  \
make_model                                                     Audi A1   
body_type                                                       Sedans   
price                                                            15770   
vat                                                     VAT deductible   
km                                                           56013.000   
previous_owners                                                  2.000   
next_inspection                                                06/2021   
inspection_new                                                     Yes   
body_color                                                       Black   
paint_type                                                    Metallic   
num_of_doors                                                     5.000   
num_of_seats                                                     5.000   
gearing_type                                                 Automatic   
cylinders                                                        3.000   
drive_chain                                                      front   
fuel                                                            Diesel   
consumption          [['3.8 l/100 km (comb)'], ['4.3 l/100 km (city...   
co2_emission                                                    99.000   
emission_class                                                  Euro 6   
comfort_convenience  Air conditioning, Armrest, Automatic climate c...   
entertainment_media  Bluetooth, Hands-free equipment, On-board comp...   
extras                Alloy wheels, Catalytic Converter, Voice Control   
safety_security      ABS, Central door lock, Daytime running lights...   
gears                                                              NaN   
age                                                              3.000   
hp_kw                                                           66.000   
type                                                              Used   
warranty_months                                                    NaN   
upholstery_type                                                  Cloth   
upholstery_color                                                 Black   
displacement_cc                                               1422.000   
weight_kg                                                     1220.000   
cons_comb                                                        3.800   
cons_city                                                        4.300   
cons_country                                                     3.500   

                                                                     1  \
make_model                                                     Audi A1   
body_type                                                       Sedans   
price                                                            14500   
vat                                                   Price negotiable   
km                                                           80000.000   
previous_owners                                                    NaN   
next_inspection                                                    NaN   
inspection_new                                                     NaN   
body_color                                                         Red   
paint_type                                                         NaN   
num_of_doors                                                     3.000   
num_of_seats                                                     4.000   
gearing_type                                                 Automatic   
cylinders                                                        4.000   
drive_chain                                                      front   
fuel                                                           Benzine   
consumption          [['5.6 l/100 km (comb)'], ['7.1 l/100 km (city...   
co2_emission                                                   129.000  

In [843]:
df.shape

(15919, 35)

In [844]:
df.describe()

price         km  previous_owners  num_of_doors  num_of_seats  \
count 15919.000  14895.000         9279.000     15707.000     14942.000   
mean  18019.897  34130.128            1.068         4.656         4.950   
std    7386.169  37352.978            0.330         0.645         0.490   
min      13.000      0.000            0.000         1.000         2.000   
25%   12850.000   5153.000            1.000         4.000         5.000   
50%   16900.000  22740.000            1.000         5.000         5.000   
75%   21900.000  49371.500            1.000         5.000         5.000   
max   74600.000 317000.000            4.000         7.000         7.000   

       cylinders  co2_emission     gears       age     hp_kw  warranty_months  \
count  10239.000     13483.000 11207.000 14322.000 15831.000         4853.000   
mean       3.797       109.291     5.925     1.542    88.368           21.927   
std        0.415        36.193     0.848     1.077    26.835           15.771   
min        1.000         0.000     1.000     0.000     1.000            1.000   
25%        4.000       103.000     5.000     1.000    66.000           12.000   
50%        4.000       114.000     6.000     1.000    85.000           12.000   
75%        4.000       128.000     6.000     3.000   101.000           24.000   
max        8.000       990.000    50.000     3.000   294.000           72.000   

       displacement_cc  weight_kg  cons_comb  cons_city  cons_country  
count        15423.000   8945.000  13886.000  13483.000     13543.000  
mean          1423.541   1351.107      4.896      5.948         4.238  
std            333.531    220.662      1.635      1.967         1.194  
min              1.000      1.000      0.000      0.000         0.000  
25%           1229.000   1165.000      4.100      4.700         3.700  
50%           1461.000   1288.000      4.800      5.800         4.200  
75%           1598.000   1487.000      5.500      7.000         4.600  
max          16000.000   2471.000     55.000     66.000        44.000

In [845]:
df.columns

Index(['make_model', 'body_type', 'price', 'vat', 'km', 'previous_owners',
       'next_inspection', 'inspection_new', 'body_color', 'paint_type',
       'num_of_doors', 'num_of_seats', 'gearing_type', 'cylinders',
       'drive_chain', 'fuel', 'consumption', 'co2_emission', 'emission_class',
       'comfort_convenience', 'entertainment_media', 'extras',
       'safety_security', 'gears', 'age', 'hp_kw', 'type', 'warranty_months',
       'upholstery_type', 'upholstery_color', 'displacement_cc', 'weight_kg',
       'cons_comb', 'cons_city', 'cons_country'],
      dtype='object')

In [846]:
(df.isnull().sum()/df.shape[0]*100).sort_values(ascending=False)
#(df.isnull().sum()/df.isnull().count()*100).sort_values(ascending=False)


next_inspection       77.794
inspection_new        75.300
warranty_months       69.514
weight_kg             43.809
drive_chain           43.081
previous_owners       41.711
paint_type            36.259
cylinders             35.681
upholstery_color      31.899
upholstery_type       30.599
gears                 29.600
vat                   28.350
emission_class        22.790
extras                18.607
co2_emission          15.302
cons_city             15.302
cons_country          14.926
cons_comb             12.771
consumption           11.973
age                   10.032
entertainment_media    8.631
km                     6.433
safety_security        6.169
num_of_seats           6.137
comfort_convenience    5.779
body_color             3.750
displacement_cc        3.116
num_of_doors           1.332
hp_kw                  0.553
body_type              0.377
type                   0.013
gearing_type           0.000
fuel                   0.000
price                  0.000
make_model    

In [847]:
miss_val = []
[miss_val.append(i) for i in df.columns if any(df[i].isnull())]  
# df[i].isnull().any() same :D
miss_val


['body_type',
 'vat',
 'km',
 'previous_owners',
 'next_inspection',
 'inspection_new',
 'body_color',
 'paint_type',
 'num_of_doors',
 'num_of_seats',
 'cylinders',
 'drive_chain',
 'consumption',
 'co2_emission',
 'emission_class',
 'comfort_convenience',
 'entertainment_media',
 'extras',
 'safety_security',
 'gears',
 'age',
 'hp_kw',
 'type',
 'warranty_months',
 'upholstery_type',
 'upholstery_color',
 'displacement_cc',
 'weight_kg',
 'cons_comb',
 'cons_city',
 'cons_country']

In [848]:
missing_count = df.isnull().sum().sort_values(ascending=False)
missing_per = (df.isnull().sum()/df.shape[0]*100).sort_values(ascending=False)

missing_df = pd.concat({"missing_count": missing_count,
                       "missing_percentage": missing_per}, axis=1)
missing_df


missing_count  missing_percentage
next_inspection              12384              77.794
inspection_new               11987              75.300
warranty_months              11066              69.514
weight_kg                     6974              43.809
drive_chain                   6858              43.081
previous_owners               6640              41.711
paint_type                    5772              36.259
cylinders                     5680              35.681
upholstery_color              5078              31.899
upholstery_type               4871              30.599
gears                         4712              29.600
vat                           4513              28.350
emission_class                3628              22.790
extras                        2962              18.607
co2_emission                  2436              15.302
cons_city                     2436              15.302
cons_country                  2376              14.926
cons_comb                     2033              12.771
consumption                   1906              11.973
age                           1597              10.032
entertainment_media           1374               8.631
km                            1024               6.433
safety_security                982               6.169
num_of_seats                   977               6.137
comfort_convenience            920               5.779
body_color                     597               3.750
displacement_cc                496               3.116
num_of_doors                   212               1.332
hp_kw                           88               0.553
body_type                       60               0.377
type                             2               0.013
gearing_type                     0               0.000
fuel                             0               0.000
price                            0               0.000
make_model                       0               0.000

### Examining and filling the missing values of the features one by one

### warranty_months

In [849]:
print('\n''Percentage of Missing Values : ', round(df['warranty_months'].isnull().sum()/df.shape[0]*100, 2), '\n')
print("Number of Missings           : ",
      df['warranty_months'].isnull().sum(), '\n')
print("Number of Uniques            : ", df['warranty_months'].nunique(), '\n')
print('Value counts                 : ''\n''\n',df['warranty_months'].value_counts(dropna=False))



Percentage of Missing Values :  69.51 

Number of Missings           :  11066 

Number of Uniques            :  41 

Value counts                 : 

 NaN       11066
12.000     2594
24.000     1118
60.000      401
36.000      279
48.000      149
6.000       125
72.000       59
3.000        33
23.000       11
18.000       10
20.000        7
25.000        6
2.000         5
50.000        4
26.000        4
16.000        4
4.000         3
1.000         3
19.000        3
34.000        3
13.000        3
28.000        2
22.000        2
14.000        2
11.000        2
46.000        2
21.000        2
9.000         2
17.000        2
45.000        2
33.000        1
40.000        1
65.000        1
10.000        1
15.000        1
7.000         1
8.000         1
56.000        1
49.000        1
47.000        1
30.000        1
Name: warranty_months, dtype: int64


In [850]:
df.dtypes['warranty_months']


dtype('float64')

In [851]:
df['warranty_months'].isin(['?']).any()

False

In [852]:
df['warranty_months'].isin(['-']).any()


False

In [853]:
df.groupby(['make_model', 'age']).warranty_months.mean()


make_model      age  
Audi A1         0.000   28.137
                1.000   26.300
                2.000   17.679
                3.000   13.926
Audi A2         1.000      NaN
Audi A3         0.000   27.171
                1.000   21.707
                2.000   16.655
                3.000   17.112
Opel Astra      0.000   39.595
                1.000   25.795
                2.000   14.988
                3.000   24.797
Opel Corsa      0.000   29.059
                1.000   17.355
                2.000   22.148
                3.000   27.061
Opel Insignia   0.000   33.676
                1.000   25.354
                2.000   17.024
                3.000   15.225
Renault Clio    0.000   32.522
                1.000   15.686
                2.000   16.733
                3.000   10.864
Renault Duster  0.000   12.000
Renault Espace  0.000   32.472
                1.000   22.524
                2.000   14.934
                3.000   12.482
Name: warranty_months, dtype: float64

In [854]:
df.groupby(['make_model', 'age'])['warranty_months'].mean()


make_model      age  
Audi A1         0.000   28.137
                1.000   26.300
                2.000   17.679
                3.000   13.926
Audi A2         1.000      NaN
Audi A3         0.000   27.171
                1.000   21.707
                2.000   16.655
                3.000   17.112
Opel Astra      0.000   39.595
                1.000   25.795
                2.000   14.988
                3.000   24.797
Opel Corsa      0.000   29.059
                1.000   17.355
                2.000   22.148
                3.000   27.061
Opel Insignia   0.000   33.676
                1.000   25.354
                2.000   17.024
                3.000   15.225
Renault Clio    0.000   32.522
                1.000   15.686
                2.000   16.733
                3.000   10.864
Renault Duster  0.000   12.000
Renault Espace  0.000   32.472
                1.000   22.524
                2.000   14.934
                3.000   12.482
Name: warranty_months, dtype: float64

In [855]:
df['warranty_months'].fillna(df.groupby(['make_model', 'age'], as_index=True)[
    "warranty_months"].transform(lambda x: pd.Series.mean(x)), inplace=True)


In [856]:
df.warranty_months.isnull().sum()
# I still have more missing values!!

1283

In [857]:
df.groupby(["make_model", "warranty_months"]).price.describe().sort_values(
    by=["make_model", "mean"], ascending=False)


count      mean      std       min       25%  \
make_model     warranty_months                                                  
Renault Espace 32.472          169.000 40456.497 8081.822 28890.000 32975.000   
               48.000           14.000 39806.786 8058.500 19490.000 37035.000   
               16.000            1.000 38890.000      NaN 38890.000 38890.000   
               45.000            1.000 37950.000      NaN 37950.000 37950.000   
               23.000            1.000 37600.000      NaN 37600.000 37600.000   
...                                ...       ...      ...       ...       ...   
Audi A1        47.000            1.000 16370.000      NaN 16370.000 16370.000   
               49.000            1.000 16270.000      NaN 16270.000 16270.000   
               46.000            1.000 15980.000      NaN 15980.000 15980.000   
               26.000            1.000 15840.000      NaN 15840.000 15840.000   
               13.926          480.000 14526.779 1877.216  8999.000 13400.000   

                                     50%       75%       max  
make_model     warranty_months                                
Renault Espace 32.472          39070.000 45490.000 64332.000  
               48.000          40692.500 46095.000 47990.000  
               16.000          38890.000 38890.000 38890.000  
               45.000          37950.000 37950.000 37950.000  
               23.000          37600.000 37600.000 37600.000  
...                                  ...       ...       ...  
Audi A1        47.000          16370.000 16370.000 16370.000  
               49.000          16270.000 16270.000 16270.000  
               46.000          15980.000 15980.000 15980.000  
               26.000          15840.000 15840.000 15840.000  
               13.926          13995.000 15750.000 19900.000  

[149 rows x 8 columns]

In [858]:
df.groupby(['make_model', 'age', 'warranty_months']).price.describe()


count      mean      std       min  \
make_model     age   warranty_months                                        
Audi A1        0.000 12.000           37.000 23712.459 2901.720 17900.000   
                     18.000            1.000 19995.000      NaN 19995.000   
                     24.000           75.000 24087.000 3070.452 15550.000   
                     28.137          323.000 24407.065 3216.722 15990.000   
                     36.000           16.000 26054.875 2778.758 21500.000   
...                                      ...       ...      ...       ...   
Renault Espace 3.000 11.000            1.000 14999.000      NaN 14999.000   
                     1.000             1.000 20745.000      NaN 20745.000   
                     21.000            1.000 25990.000      NaN 25990.000   
                     12.482          161.000 21931.559 3562.319 12614.000   
                     40.000            1.000 22500.000      NaN 22500.000   

                                           25%       50%       75%       max  
make_model     age   warranty_months                                          
Audi A1        0.000 12.000          21000.000 23400.000 25500.000 28990.000  
                     18.000          19995.000 19995.000 19995.000 19995.000  
                     24.000          21945.000 23300.000 26890.000 32000.000  
                     28.137          21920.000 24450.000 27200.000 37900.000  
                     36.000          24092.500 27050.000 28532.500 29179.000  
...                                        ...       ...       ...       ...  
Renault Espace 3.000 11.000          14999.000 14999.000 14999.000 14999.000  
                     1.000           20745.000 20745.000 20745.000 20745.000  
                     21.000          25990.000 25990.000 25990.000 25990.000  
                     12.482          19013.000 21900.000 24899.000 30000.000  
                     40.000          22500.000 22500.000 22500.000 22500.000  

[255 rows x 8 columns]

There are too many NaN standard deviation values. If these Nan values were not present, this column would be important when evaluating the price column. I am dropping it.

In [859]:
df.drop('warranty_months', axis=1, inplace=True)


In [860]:
df.columns

Index(['make_model', 'body_type', 'price', 'vat', 'km', 'previous_owners',
       'next_inspection', 'inspection_new', 'body_color', 'paint_type',
       'num_of_doors', 'num_of_seats', 'gearing_type', 'cylinders',
       'drive_chain', 'fuel', 'consumption', 'co2_emission', 'emission_class',
       'comfort_convenience', 'entertainment_media', 'extras',
       'safety_security', 'gears', 'age', 'hp_kw', 'type', 'upholstery_type',
       'upholstery_color', 'displacement_cc', 'weight_kg', 'cons_comb',
       'cons_city', 'cons_country'],
      dtype='object')

### age column:

In [861]:
print('\n''Percentage of Missing Values : ', round(df['age'].isnull().sum()/df.shape[0]*100, 2), '\n')
print("Number of Missings           : ",
      df['age'].isnull().sum(), '\n')
print("Number of Uniques            : ", df['age'].nunique(), '\n')
print('Value counts                 : ''\n''\n',df['age'].value_counts(dropna=False))


Percentage of Missing Values :  10.03 

Number of Missings           :  1597 

Number of Uniques            :  4 

Value counts                 : 

 1.000    4522
3.000    3674
2.000    3273
0.000    2853
NaN      1597
Name: age, dtype: int64


In [862]:
df['age'].fillna('-', inplace=True)
# I replaced NaN with '-' so that I can see the statistical data of the NaN values.

In [863]:
df.groupby("age").price.describe()


count      mean      std      min       25%       50%       75%  \
age                                                                      
0.0 2853.000 22805.061 9198.275  120.000 15890.000 22950.000 27290.000   
1.0 4522.000 18456.037 6038.583   13.000 14800.000 18490.000 21700.000   
2.0 3273.000 15595.916 5265.701 6000.000 11600.000 15750.000 18900.000   
3.0 3674.000 13644.039 4439.875 4950.000 10400.000 13884.000 15980.000   
-   1597.000 23271.175 7888.608 6490.000 17990.000 22995.000 27380.000   

          max  
age            
0.0 64332.000  
1.0 74600.000  
2.0 67600.000  
3.0 42500.000  
-   68320.000

In [864]:
df.groupby("age").km.describe()


count      mean       std    min       25%       50%       75%  \
age                                                                     
0.0 2706.000  2085.355  5365.881  1.000    10.000    50.000  3000.000   
1.0 4484.000 18035.239 11052.524  1.000  9990.000 17872.000 25078.500   
2.0 3272.000 41754.941 28295.748  1.000 21541.750 34752.000 54805.500   
3.0 3674.000 77442.521 39170.143 10.000 48000.000 72914.500 99950.000   
-    759.000   934.497  7416.244  0.000     5.000    10.000    10.000   

           max  
age             
0.0 127022.000  
1.0 136000.000  
2.0 317000.000  
3.0 291800.000  
-    89982.000

When the describe() table is examined, the average (km), Q1 (km) and Q3 (km) values for the age category can be seen. According to these values, it is possible to fill in the missing values in the age category.

In [865]:
# setting conditions according to km values

age_0 = (df['km'] < 10000)
age_1 = ((df['km'] >= 10000) & (df['km'] <= 25000))
age_2 = ((df['km'] > 28000) & (df['km'] <= 54000))
age_3 = (df['km'] > 54000)


In [866]:
df.loc[age_0,'age'] = df.loc[age_0,'age'].replace('-', 0)
df.loc[age_1,'age'] = df.loc[age_1,'age'].replace('-', 1)
df.loc[age_2,'age'] = df.loc[age_2,'age'].replace('-', 2)
df.loc[age_3,'age'] = df.loc[age_3,'age'].replace('-', 3)

In [867]:
df.age.value_counts(dropna=False)

1.0    4528
3.0    3679
0.0    3597
2.0    3277
-       838
Name: age, dtype: int64

I filled age column according to km column, but i stil have missing values in age column. Why? 
Can i have missing values in km column too? ---> Yes, there are 1024 missing values in km column.

In [868]:
df.km.isnull().sum()

1024

In [869]:
df[df["age"]=='-']["km"]

743     NaN
869     NaN
946     NaN
977     NaN
980     NaN
         ..
15888   NaN
15890   NaN
15902   NaN
15912   NaN
15914   NaN
Name: km, Length: 838, dtype: float64

In [870]:
df.groupby(['make_model', 'age']).price.mean()


make_model      age
Audi A1         0.0   23876.269
                1.0   18446.178
                2.0   16625.734
                3.0   14489.769
                -     23842.852
Audi A2         1.0   28200.000
Audi A3         0.0   25045.758
                1.0   22504.332
                2.0   19939.557
                3.0   16466.090
                -     24172.609
Opel Astra      0.0   21621.258
                1.0   16134.623
                2.0   13008.951
                3.0   11357.733
                -     19913.439
Opel Corsa      0.0   13455.006
                1.0   11304.836
                2.0    9249.490
                3.0    8195.207
                -     13717.625
Opel Insignia   0.0   33633.709
                1.0   21377.004
                2.0   16995.141
                3.0   13606.710
                -     29016.103
Renault Clio    0.0   11912.385
                1.0   14698.492
                2.0   10814.541
                3.0    9349.533
                -   

When I make a grouping by 'make_model' and 'age' and examine the 'price' column, I see that the price.mean() of the remaining missing values corresponds to the price.mean() value of 'age'=0 column. I can fill the remaining missing values with 0.

In [871]:
df['age'].replace('-',0, inplace=True)

In [872]:
df.age.value_counts(dropna=False)

1.000    4528
0.000    4435
3.000    3679
2.000    3277
Name: age, dtype: int64

Now i want to continue with km column.

### km column:

In [873]:
print('\n''Percentage of Missing Values : ', round(df['km'].isnull().sum()/df.shape[0]*100, 2), '\n')
print("Number of Missings           : ",
      df['km'].isnull().sum(), '\n')
print("Number of Uniques            : ", df['km'].nunique(), '\n')
print('Value counts                 : ''\n''\n',df['km'].value_counts(dropna=False))


Percentage of Missing Values :  6.43 

Number of Missings           :  1024 

Number of Uniques            :  6689 

Value counts                 : 

 10.000       1045
NaN          1024
1.000         367
5.000         170
50.000        148
             ... 
67469.000       1
43197.000       1
10027.000       1
35882.000       1
57.000          1
Name: km, Length: 6690, dtype: int64


There are 1024 missing values in this column. If I find the average km values by age, can I fill in the missing values?

In [874]:
df.groupby("age").km.mean()


age
0.000    1647.363
1.000   18035.130
2.000   41748.577
3.000   77450.063
Name: km, dtype: float64

In [875]:
df.groupby('age')["km"].transform(lambda x: pd.Series.mean(x))


0       77450.063
1       41748.577
2       77450.063
3       77450.063
4       77450.063
           ...   
15914    1647.363
15915    1647.363
15916    1647.363
15917    1647.363
15918    1647.363
Name: km, Length: 15919, dtype: float64

In [876]:
df['km'].fillna(df.groupby('age')["km"].transform(lambda x: pd.Series.mean(x)), inplace=True)


In [877]:
df.km.isnull().sum()

0

In [878]:
df.km.value_counts(dropna=False)

10.000       1045
1647.363      985
1.000         367
5.000         170
50.000        148
             ... 
67469.000       1
43197.000       1
10027.000       1
35882.000       1
57.000          1
Name: km, Length: 6692, dtype: int64

There is no missing value in this column anymore.

In [879]:
df.columns

Index(['make_model', 'body_type', 'price', 'vat', 'km', 'previous_owners',
       'next_inspection', 'inspection_new', 'body_color', 'paint_type',
       'num_of_doors', 'num_of_seats', 'gearing_type', 'cylinders',
       'drive_chain', 'fuel', 'consumption', 'co2_emission', 'emission_class',
       'comfort_convenience', 'entertainment_media', 'extras',
       'safety_security', 'gears', 'age', 'hp_kw', 'type', 'upholstery_type',
       'upholstery_color', 'displacement_cc', 'weight_kg', 'cons_comb',
       'cons_city', 'cons_country'],
      dtype='object')

### body_type column:

In [880]:
print('\n''Percentage of Missing Values : ', round(
    df['body_type'].isnull().sum()/df.shape[0]*100, 2), '\n')
print("Number of Missings           : ",
      df['body_type'].isnull().sum(), '\n')
print("Number of Uniques            : ", df['body_type'].nunique(), '\n')
print('Value counts                 : ''\n''\n',df['body_type'].value_counts(dropna=False))


Percentage of Missing Values :  0.38 

Number of Missings           :  60 

Number of Uniques            :  9 

Value counts                 : 

 Sedans           7903
Station wagon    3553
Compact          3153
Van               783
Other             290
Transporter        88
NaN                60
Off-Road           56
Coupe              25
Convertible         8
Name: body_type, dtype: int64


In this column there are 60 Nan values and also 290 Other values. I am converting Other values to the NaN.

In [881]:
df.body_type.replace("Other", np.nan, inplace=True)
df['body_type'].value_counts(dropna=False)


Sedans           7903
Station wagon    3553
Compact          3153
Van               783
NaN               350
Transporter        88
Off-Road           56
Coupe              25
Convertible         8
Name: body_type, dtype: int64

In [882]:
df.body_type.describe()

count      15569
unique         8
top       Sedans
freq        7903
Name: body_type, dtype: object

Most repeated value is 'Sedans' i can see that from the .describe()--->top and also with mode() function

In [883]:
df.body_type.mode()

0    Sedans
Name: body_type, dtype: object

In [884]:
list(df["make_model"].unique())


['Audi A1',
 'Audi A2',
 'Audi A3',
 'Opel Astra',
 'Opel Corsa',
 'Opel Insignia',
 'Renault Clio',
 'Renault Duster',
 'Renault Espace']

There are 9 unique value in make_model column. We can find most repeated body_type for each unique value.

In [885]:
df[df["make_model"]=="Audi A1"]["body_type"].mode()

0    Sedans
Name: body_type, dtype: object

It would be better if we could do it for all at once.

In [886]:
def fill_most(df, group_col, col_name):
    #Fills the missing values with the most existing value (mode) in the relevant column according to single-stage grouping
    for group in list(df[group_col].unique()):
        cond = df[group_col] == group
        grp_inx = list(df[cond][col_name].index)
        mode = list(df[cond][col_name].mode())
        if mode != []:
            df[col_name].iloc[grp_inx] = df[col_name].iloc[grp_inx].fillna(
                df[cond][col_name].mode()[0])
        else:
            df[col_name].iloc[grp_inx] = df[col_name].iloc[grp_inx].fillna(
                df[col_name].mode()[0])
    print("Number of NaN : ", df[col_name].isnull().sum())
    print("------------------")
    print(df[col_name].value_counts(dropna=False))


hier our group_col is make_model and col_name is body_type:

for make_model in list(df["make_model"].unique()):
    cond = df["make_model"] == make_model
    (we are taking our make_model's most repeated body_type and assigning it mode)
    mode = list(df[cond]["body_type"].mode())
    if mode != []:
        (filling our body_type with most repeated body type of our make_model)
        df.loc[cond, "body_type"] = df.loc[cond, "body_type"].fillna(df[cond]["body_type"].mode()[0])
    else:
        df.loc[cond, "body_type"] = df.loc[cond, "body_type"].fillna(df["body_type"].mode()[0])

In [887]:
fill_most(df, 'make_model', 'body_type')


Number of NaN :  0
------------------
Sedans           8005
Station wagon    3678
Compact          3242
Van               817
Transporter        88
Off-Road           56
Coupe              25
Convertible         8
Name: body_type, dtype: int64


In [888]:
df.columns

Index(['make_model', 'body_type', 'price', 'vat', 'km', 'previous_owners',
       'next_inspection', 'inspection_new', 'body_color', 'paint_type',
       'num_of_doors', 'num_of_seats', 'gearing_type', 'cylinders',
       'drive_chain', 'fuel', 'consumption', 'co2_emission', 'emission_class',
       'comfort_convenience', 'entertainment_media', 'extras',
       'safety_security', 'gears', 'age', 'hp_kw', 'type', 'upholstery_type',
       'upholstery_color', 'displacement_cc', 'weight_kg', 'cons_comb',
       'cons_city', 'cons_country'],
      dtype='object')

### vat column:

In [889]:
print('\n''Percentage of Missing Values : %', round(df['vat'].isnull().sum()/df.shape[0]*100, 2), '\n')
print("Number of Missings           : ",
      df['vat'].isnull().sum(), '\n')
print("Number of Uniques            : ", df['vat'].nunique(), '\n')
print('Value counts                 : ''\n''\n',df['vat'].value_counts(dropna=False))


Percentage of Missing Values : % 28.35 

Number of Missings           :  4513 

Number of Uniques            :  2 

Value counts                 : 

 VAT deductible      10980
NaN                  4513
Price negotiable      426
Name: vat, dtype: int64


We can use fillna ffill and bfill for this column

In [890]:
df['vat'].fillna(method="ffill").fillna(method="bfill")


0          VAT deductible
1        Price negotiable
2          VAT deductible
3          VAT deductible
4          VAT deductible
               ...       
15914      VAT deductible
15915      VAT deductible
15916      VAT deductible
15917      VAT deductible
15918      VAT deductible
Name: vat, Length: 15919, dtype: object

In [891]:
df['vat'] = df['vat'].fillna(method="ffill").fillna(method="bfill")


In [892]:
df.vat.value_counts(dropna=False)

VAT deductible      15048
Price negotiable      871
Name: vat, dtype: int64

### previous_owners column:

In [893]:
print('\n''Percentage of Missing Values : %', round(
    df['previous_owners'].isnull().sum()/df.shape[0]*100, 2), '\n')
print("Number of Missings           : ",
      df['previous_owners'].isnull().sum(), '\n')
print("Number of Uniques            : ", df['previous_owners'].nunique(), '\n')
print('Value counts                 : ''\n''\n',df['previous_owners'].value_counts(dropna=False))


Percentage of Missing Values : % 41.71 

Number of Missings           :  6640 

Number of Uniques            :  5 

Value counts                 : 

 1.000    8294
NaN      6640
2.000     778
0.000     188
3.000      17
4.000       2
Name: previous_owners, dtype: int64


In [894]:
df["previous_owners"].fillna("-", inplace=True)


In [895]:
df.previous_owners.value_counts(dropna=False)

1.0    8294
-      6640
2.0     778
0.0     188
3.0      17
4.0       2
Name: previous_owners, dtype: int64

In [896]:
df.groupby(['make_model', 'age', 'previous_owners']).km.describe()


count      mean       std       min  \
make_model     age   previous_owners                                         
Audi A1        0.000 0.0              45.000   958.365   815.362     0.000   
                     1.0             239.000  3069.543  3460.402     1.000   
                     2.0               1.000  3000.000       NaN  3000.000   
                     -               521.000  1549.992  2303.800     1.000   
               1.000 0.0               1.000 15000.000       NaN 15000.000   
...                                      ...       ...       ...       ...   
Renault Espace 3.000 1.0             118.000 79365.805 36296.880  3532.000   
                     2.0              20.000 55316.250 27356.183  7300.000   
                     3.0               1.000 40000.000       NaN 40000.000   
                     4.0               1.000 57000.000       NaN 57000.000   
                     -               159.000 73332.057 32702.200  6119.000   

                                           25%       50%       75%        max  
make_model     age   previous_owners                                           
Audi A1        0.000 0.0                10.000  1647.363  1647.363   1647.363  
                     1.0                20.000  2500.000  5000.000  18000.000  
                     2.0              3000.000  3000.000  3000.000   3000.000  
                     -                  11.000  1647.363  1647.363  15500.000  
               1.000 0.0             15000.000 15000.000 15000.000  15000.000  
...                                        ...       ...       ...        ...  
Renault Espace 3.000 1.0             55000.000 76475.000 98375.750 197414.000  
                     2.0             42536.750 51972.500 64921.250 148000.000  
                     3.0             40000.000 40000.000 40000.000  40000.000  
                     4.0             57000.000 57000.000 57000.000  57000.000  
                     -               50027.000 68570.000 94000.000 169068.000  

[120 rows x 8 columns]

In [897]:
list(df.make_model.unique())

['Audi A1',
 'Audi A2',
 'Audi A3',
 'Opel Astra',
 'Opel Corsa',
 'Opel Insignia',
 'Renault Clio',
 'Renault Duster',
 'Renault Espace']

In [898]:
df[(df["make_model"]=="Opel Insignia") & (df["previous_owners"] == "-")][["make_model", "previous_owners", "km", 'age']].sample(10)

make_model previous_owners        km   age
12752  Opel Insignia               -  1647.363 0.000
10904  Opel Insignia               - 78225.000 2.000
12930  Opel Insignia               -  6800.000 0.000
11194  Opel Insignia               - 73130.000 3.000
10957  Opel Insignia               - 34780.000 2.000
12823  Opel Insignia               -  1647.363 0.000
10837  Opel Insignia               - 99000.000 2.000
12787  Opel Insignia               -   100.000 0.000
12476  Opel Insignia               -    10.000 0.000
10955  Opel Insignia               - 34780.000 2.000

In [899]:
df[(df["make_model"]=="Renault Clio") & (df["previous_owners"] == "-")][["make_model", "previous_owners", "km", 'age']].sample(10)

make_model previous_owners         km   age
14876  Renault Clio               -      5.000 0.000
13632  Renault Clio               - 135050.000 3.000
14622  Renault Clio               -     99.000 1.000
14538  Renault Clio               -      7.000 0.000
13318  Renault Clio               -  25500.000 3.000
14825  Renault Clio               -     10.000 0.000
13830  Renault Clio               -  22000.000 1.000
13654  Renault Clio               -  98694.000 3.000
13200  Renault Clio               -  42504.000 3.000
13257  Renault Clio               -   1647.363 0.000

In [900]:
df[(df["make_model"]=="Renault Clio") & (df["previous_owners"] == 2.0)][["make_model", "previous_owners", "km", 'age']].sample(10)

make_model previous_owners        km   age
13301  Renault Clio           2.000 20500.000 3.000
13967  Renault Clio           2.000 30000.000 2.000
13458  Renault Clio           2.000 49178.000 3.000
13799  Renault Clio           2.000 54413.000 2.000
14586  Renault Clio           2.000   500.000 0.000
13467  Renault Clio           2.000 49178.000 3.000
13463  Renault Clio           2.000 49178.000 3.000
13466  Renault Clio           2.000 49178.000 3.000
14394  Renault Clio           2.000  5210.000 1.000
13818  Renault Clio           2.000 44000.000 3.000

In [901]:
df[(df["make_model"]=="Renault Clio")][["make_model", "previous_owners", "km", 'age']].sample(10)

make_model previous_owners        km   age
13475  Renault Clio               - 43709.000 2.000
14354  Renault Clio               - 21197.000 1.000
13930  Renault Clio           1.000 46610.000 2.000
14777  Renault Clio           0.000    10.000 0.000
13302  Renault Clio               - 24700.000 1.000
13960  Renault Clio               -    10.000 0.000
13720  Renault Clio           1.000 98000.000 3.000
14646  Renault Clio               -     1.000 0.000
14468  Renault Clio               -    10.000 0.000
14823  Renault Clio           1.000    10.000 0.000

In [902]:
df[(df["make_model"]=="Renault Duster")][["make_model", "previous_owners", "km", 'age']].sample(10)

make_model previous_owners       km   age
14926  Renault Duster               -  101.000 0.000
14925  Renault Duster               -  101.000 0.000
14918  Renault Duster               - 1647.363 0.000
14908  Renault Duster               - 1647.363 0.000
14898  Renault Duster               -  101.000 0.000
14909  Renault Duster               - 1647.363 0.000
14923  Renault Duster               -  101.000 0.000
14896  Renault Duster               -  101.000 0.000
14914  Renault Duster               -  101.000 0.000
14919  Renault Duster               - 1647.363 0.000

I can fill this column with fillna(ffill and bfill) method.

In [903]:
df["previous_owners"] = df["previous_owners"].replace("-", np.nan)


In [904]:
df.previous_owners.value_counts(dropna=False)

1.000    8294
NaN      6640
2.000     778
0.000     188
3.000      17
4.000       2
Name: previous_owners, dtype: int64

In [905]:
def fill_prop(df, group_col, col_name):
    #Fills the missing values with \"ffill and bfill method\" according to single-stage grouping
    for group in list(df[group_col].unique()):
        cond = df[group_col] == group
        grp_inx = list(df[cond][col_name].index)
        df.loc[cond, col_name] = df.loc[cond, col_name].fillna(method="ffill").fillna(method="bfill")
    df[col_name] = df[col_name].fillna(method="ffill").fillna(method="bfill")
    print("Number of NaN : ", df[col_name].isnull().sum())
    print("------------------")
    print(df[col_name].value_counts(dropna=False))


In [906]:
fill_prop(df, "age", "previous_owners")


Number of NaN :  0
------------------
1.000    14170
2.000     1172
0.000      546
3.000       29
4.000        2
Name: previous_owners, dtype: int64


In [907]:
df.columns

Index(['make_model', 'body_type', 'price', 'vat', 'km', 'previous_owners',
       'next_inspection', 'inspection_new', 'body_color', 'paint_type',
       'num_of_doors', 'num_of_seats', 'gearing_type', 'cylinders',
       'drive_chain', 'fuel', 'consumption', 'co2_emission', 'emission_class',
       'comfort_convenience', 'entertainment_media', 'extras',
       'safety_security', 'gears', 'age', 'hp_kw', 'type', 'upholstery_type',
       'upholstery_color', 'displacement_cc', 'weight_kg', 'cons_comb',
       'cons_city', 'cons_country'],
      dtype='object')

### inspection_new column:

In [908]:
print('\n''Percentage of Missing Values : %', round(
    df['inspection_new'].isnull().sum()/df.shape[0]*100, 2), '\n')
print("Number of Missings           : ",
      df['inspection_new'].isnull().sum(), '\n')
print("Number of Uniques            : ", df['inspection_new'].nunique(), '\n')
print('Value counts                 : ''\n''\n',df['inspection_new'].value_counts(dropna=False))


Percentage of Missing Values : % 75.3 

Number of Missings           :  11987 

Number of Uniques            :  1 

Value counts                 : 

 NaN    11987
Yes     3932
Name: inspection_new, dtype: int64


In [909]:
df.inspection_new.value_counts(dropna=False)

NaN    11987
Yes     3932
Name: inspection_new, dtype: int64

In this column we have only 2 values; NaN and 'Yes'.

In [910]:
df["inspection_new"].fillna("-", inplace=True)


In [911]:
df.inspection_new.value_counts(dropna=False)


-      11987
Yes     3932
Name: inspection_new, dtype: int64

In [912]:
df.groupby(["make_model", "age", 'km', "inspection_new"]).price.describe()


count      mean      std  \
make_model     age   km         inspection_new                             
Audi A1        0.000 0.000      -               2.000 23999.500 8485.988   
                                Yes             2.000 22720.000    0.000   
                     1.000      -              49.000 22068.429 2826.160   
                     5.000      -               2.000 24595.000 5225.519   
                     6.000      -               3.000 23475.000    0.000   
...                                               ...       ...      ...   
Renault Espace 3.000 152736.000 -               1.000 13500.000      NaN   
                     169068.000 -               1.000 15500.000      NaN   
                     180000.000 Yes             1.000 12990.000      NaN   
                     197323.000 Yes             1.000 12614.000      NaN   
                     197414.000 -               1.000 12990.000      NaN   

                                                     min       25%       50%  \
make_model     age   km         inspection_new                                 
Audi A1        0.000 0.000      -              17999.000 20999.250 23999.500   
                                Yes            22720.000 22720.000 22720.000   
                     1.000      -              17330.000 20850.000 21290.000   
                     5.000      -              20900.000 22747.500 24595.000   
                     6.000      -              23475.000 23475.000 23475.000   
...                                                  ...       ...       ...   
Renault Espace 3.000 152736.000 -              13500.000 13500.000 13500.000   
                     169068.000 -              15500.000 15500.000 15500.000   
                     180000.000 Yes            12990.000 12990.000 12990.000   
                     197323.000 Yes            12614.000 12614.000 12614.000   
                     197414.000 -              12990.000 12990.000 12990.000   

                                                     75%       max  
make_model     age   km         inspection_new                      
Audi A1        0.000 0.000      -              26999.750 30000.000  
                                Yes            22720.000 22720.000  
                     1.000      -              23900.000 32000.000  
                     5.000      -              26442.500 28290.000  
                     6.000      -              23475.000 23475.000  
...                                                  ...       ...  
Renault Espace 3.000 152736.000 -              13500.000 13500.000  
                     169068.000 -              15500.000 15500.000  
                     180000.000 Yes            12990.000 12990.000  
                     197323.000 Yes            12614.000 12614.000  
                     197414.000 -              12990.000 12990.000  

[9882 rows x 8 columns]

In [913]:
df[(df["inspection_new"] == 'Yes')][["make_model", "inspection_new", "km", 'age']].sample(10)

make_model inspection_new        km   age
14384    Renault Clio            Yes     1.000 1.000
12036   Opel Insignia            Yes 22712.000 1.000
1929          Audi A1            Yes  1647.363 0.000
15598  Renault Espace            Yes 29400.000 1.000
1410          Audi A1            Yes 12200.000 2.000
4666          Audi A3            Yes 27350.000 1.000
11901   Opel Insignia            Yes 15469.000 1.000
11314   Opel Insignia            Yes 30900.000 1.000
1556          Audi A1            Yes 19724.000 1.000
2516          Audi A1            Yes  1647.363 0.000

In [914]:
df[(df["make_model"] == "Renault Clio") & (df["inspection_new"] == '-')][["make_model", "inspection_new", "km", 'age']].sample(10)


make_model inspection_new        km   age
13125  Renault Clio              -    10.000 1.000
14110  Renault Clio              - 19330.000 2.000
14073  Renault Clio              -  5400.000 1.000
14303  Renault Clio              -    10.000 0.000
13179  Renault Clio              - 19528.000 2.000
14120  Renault Clio              -   150.000 0.000
14643  Renault Clio              - 35000.000 1.000
14088  Renault Clio              - 12481.000 1.000
13907  Renault Clio              - 38500.000 2.000
14791  Renault Clio              -     1.000 0.000

I can change '-' values with No

In [915]:
df["inspection_new"].replace("-", "No", inplace=True)


In [916]:
df["inspection_new"].value_counts(dropna=False)


No     11987
Yes     3932
Name: inspection_new, dtype: int64

For the modelling part yes---> 1, no---> 0

In [917]:
df["inspection_new"].replace(["Yes", "No"], [1,0], inplace = True)

In [918]:
df["inspection_new"].value_counts(dropna=False)


0    11987
1     3932
Name: inspection_new, dtype: int64

### body_color column:

In [919]:
print('\n''Percentage of Missing Values : %', round(
    df['body_color'].isnull().sum()/df.shape[0]*100, 2), '\n')
print("Number of Missings           : ",
      df['body_color'].isnull().sum(), '\n')
print("Number of Uniques            : ", df['body_color'].nunique(), '\n')
print('Value counts                 : ''\n''\n',df['body_color'].value_counts(dropna=False))


Percentage of Missing Values : % 3.75 

Number of Missings           :  597 

Number of Uniques            :  14 

Value counts                 : 

 Black     3745
Grey      3505
White     3406
Silver    1647
Blue      1431
Red        957
NaN        597
Brown      289
Green      154
Beige      108
Yellow      51
Violet      18
Bronze       6
Orange       3
Gold         2
Name: body_color, dtype: int64


In [920]:
df["body_color"].fillna("-", inplace=True)


In [921]:
df.groupby(["make_model", 'body_color']).price.describe()


count      mean      std       min       25%  \
make_model     body_color                                                  
Audi A1        -           73.000 20325.795 3601.476 12980.000 17900.000   
               Beige       17.000 18185.118 3043.361 14000.000 15960.000   
               Black      717.000 17802.365 4286.264  9950.000 14950.000   
               Blue       286.000 18872.472 4451.700 10800.000 15835.500   
               Brown       22.000 15833.045 2419.273 11445.000 13960.000   
...                           ...       ...      ...       ...       ...   
Renault Espace Brown       41.000 25306.171 8469.692 12614.000 19000.000   
               Grey       347.000 29702.801 8618.331 14999.000 23990.000   
               Silver      45.000 26658.378 5104.609 12990.000 23490.000   
               Violet      14.000 24711.214 4098.884 19900.000 21624.250   
               White      210.000 31498.605 7843.978 12990.000 27316.750   

                                50%       75%       max  
make_model     body_color                                
Audi A1        -          20080.000 22260.000 29181.000  
               Beige      17770.000 21380.000 23250.000  
               Black      16490.000 20939.000 37900.000  
               Blue       16900.000 21998.750 28990.000  
               Brown      15686.500 16812.500 20750.000  
...                             ...       ...       ...  
Renault Espace Brown      22990.000 27500.000 47990.000  
               Grey       27000.000 34165.000 64332.000  
               Silver     27990.000 29900.000 35100.000  
               Violet     24500.000 26520.000 34990.000  
               White      31900.000 34986.250 64298.000  

[84 rows x 8 columns]

In [922]:
df[(df["make_model"] == "Renault Clio") & (df["body_color"] == 'White')][["make_model", "body_color", 'age', 'price']].sample(10)


make_model body_color   age  price
14106  Renault Clio      White 1.000   9950
13460  Renault Clio      White 3.000   8490
13968  Renault Clio      White 2.000   9000
13446  Renault Clio      White 3.000   8490
13587  Renault Clio      White 2.000   7950
14478  Renault Clio      White 1.000  10490
13558  Renault Clio      White 3.000   8400
13458  Renault Clio      White 3.000   8490
13750  Renault Clio      White 3.000   6400
14341  Renault Clio      White 0.000   9990

In [923]:
df[(df["make_model"] == "Renault Clio") & (df["body_color"] == '-')
   ][["make_model", "body_color", 'age', 'price']].sample(10)


make_model body_color   age  price
14048  Renault Clio          - 0.000  16390
14690  Renault Clio          - 0.000  11462
13103  Renault Clio          - 0.000  15920
14877  Renault Clio          - 0.000  10970
14148  Renault Clio          - 0.000   9890
14487  Renault Clio          - 0.000  10564
14756  Renault Clio          - 0.000  10990
13918  Renault Clio          - 1.000   9390
13242  Renault Clio          - 3.000  13990
13864  Renault Clio          - 0.000  16990

In [924]:
df[(df["make_model"] == "Renault Clio") & (df["body_color"] == 'Black')
   ][["make_model", "body_color", 'age', 'price']].sample(10)


make_model body_color   age  price
13478  Renault Clio      Black 2.000   8490
13953  Renault Clio      Black 2.000   8990
13190  Renault Clio      Black 1.000  15485
13686  Renault Clio      Black 3.000   7280
14019  Renault Clio      Black 0.000  18087
14722  Renault Clio      Black 0.000  11299
14822  Renault Clio      Black 0.000  10980
13091  Renault Clio      Black 1.000  15990
14774  Renault Clio      Black 0.000  11165
13184  Renault Clio      Black 1.000  15485

In [925]:
df[(df["make_model"] == "Renault Clio") & (df["body_color"] == 'White') & (df["age"] == 1.000)]['price'].mean()


13012.921875

In [926]:
df[(df["make_model"] == "Renault Clio") & (df["body_color"] == 'Black') & (df["age"] == 1.000)]['price'].mean()


16835.975757575758

In [927]:
df[(df["make_model"] == "Renault Clio") & (df["body_color"] == 'Grey') & (df["age"] == 1.000)]['price'].mean()


12712.333333333334

In [928]:
df.groupby(['make_model', 'age', 'body_color'])['price'].mean()

make_model      age    body_color
Audi A1         0.000  -            21508.617
                       Black        23680.000
                       Blue         24578.415
                       Green        23093.724
                       Grey         25166.330
                                       ...   
Renault Espace  3.000  Brown        21451.074
                       Grey         22212.710
                       Silver       20620.154
                       Violet       23861.545
                       White        21381.625
Name: price, Length: 273, dtype: float64

model, km and age affect price more than color. I can drop this column.

In [929]:
df.drop("body_color", axis=1, inplace=True)


In [930]:
df.columns

Index(['make_model', 'body_type', 'price', 'vat', 'km', 'previous_owners',
       'next_inspection', 'inspection_new', 'paint_type', 'num_of_doors',
       'num_of_seats', 'gearing_type', 'cylinders', 'drive_chain', 'fuel',
       'consumption', 'co2_emission', 'emission_class', 'comfort_convenience',
       'entertainment_media', 'extras', 'safety_security', 'gears', 'age',
       'hp_kw', 'type', 'upholstery_type', 'upholstery_color',
       'displacement_cc', 'weight_kg', 'cons_comb', 'cons_city',
       'cons_country'],
      dtype='object')

### paint_type column:

In [931]:
print('\n''Percentage of Missing Values : %', round(
    df['paint_type'].isnull().sum()/df.shape[0]*100, 2))
print("Number of Missings           : ",
      df['paint_type'].isnull().sum())
print("Number of Uniques            : ", df['paint_type'].nunique())
print('Value counts                 : ''\n''\n',df['paint_type'].value_counts(dropna=False))


Percentage of Missing Values : % 36.26
Number of Missings           :  5772
Number of Uniques            :  3
Value counts                 : 

 Metallic       9794
NaN            5772
Uni/basic       347
Perl effect       6
Name: paint_type, dtype: int64


In [932]:
df["paint_type"].fillna("-", inplace=True)


In [933]:
df["paint_type"].value_counts(dropna=False)


Metallic       9794
-              5772
Uni/basic       347
Perl effect       6
Name: paint_type, dtype: int64

In [934]:
df.groupby(["make_model", "body_type", "age", 'paint_type']).price.describe()


count      mean      std  \
make_model     body_type age   paint_type                              
Audi A1        Compact   0.000 -          145.000 22082.717 3341.754   
                               Metallic   229.000 24622.258 3172.063   
                               Uni/basic    2.000 19888.000    0.000   
                         1.000 -           56.000 17590.518 2369.313   
                               Metallic   212.000 18861.651 2674.019   
...                                           ...       ...      ...   
Renault Espace Van       2.000 Metallic    91.000 26799.297 3337.258   
                               Uni/basic    1.000 29200.000      NaN   
                         3.000 -           67.000 21713.149 3450.674   
                               Metallic   136.000 22317.029 3286.732   
                               Uni/basic    3.000 22628.333 2094.722   

                                                min       25%       50%  \
make_model     body_type age   paint_type                                 
Audi A1        Compact   0.000 -          14900.000 19850.000 21490.000   
                               Metallic   17880.000 21990.000 23700.000   
                               Uni/basic  19888.000 19888.000 19888.000   
                         1.000 -          14220.000 15852.250 16864.500   
                               Metallic   13980.000 16448.750 17515.000   
...                                             ...       ...       ...   
Renault Espace Van       2.000 Metallic   16950.000 25490.000 25490.000   
                               Uni/basic  29200.000 29200.000 29200.000   
                         3.000 -          12990.000 19195.000 22900.000   
                               Metallic   12614.000 19900.000 21990.000   
                               Uni/basic  20995.000 21447.500 21900.000   

                                                75%       max  
make_model     body_type age   paint_type                      
Audi A1        Compact   0.000 -          23475.000 29181.000  
                               Metallic   27780.000 31990.000  
                               Uni/basic  19888.000 19888.000  
                         1.000 -          18367.250 23650.000  
                               Metallic   21482.500 23829.000  
...                                             ...       ...  
Renault Espace Van       2.000 Metallic   28495.000 33800.000  
                               Uni/basic  29200.000 29200.000  
                         3.000 -          23490.000 32900.000  
                               Metallic   24912.500 27900.000  
                               Uni/basic  23445.000 24990.000  

[272 rows x 8 columns]

In [935]:
df[df["make_model"] == "Audi A1"]["paint_type"].mode()


0    Metallic
Name: paint_type, dtype: object

In [936]:
df[df["make_model"] == "Renault Espace"]["paint_type"].mode()


0    Metallic
Name: paint_type, dtype: object

In [937]:
df.groupby(["make_model", "body_type", 'paint_type'])[
    ["make_model", "body_type", 'paint_type']].head()


make_model body_type paint_type
0             Audi A1    Sedans   Metallic
1             Audi A1    Sedans          -
2             Audi A1    Sedans   Metallic
3             Audi A1    Sedans   Metallic
4             Audi A1    Sedans   Metallic
...               ...       ...        ...
15545  Renault Espace    Sedans  Uni/basic
15646  Renault Espace    Sedans  Uni/basic
15785  Renault Espace     Coupe          -
15805  Renault Espace   Compact   Metallic
15905  Renault Espace   Compact   Metallic

[367 rows x 3 columns]

In [938]:
df["paint_type"].replace("-", np.nan, inplace=True)


In [939]:
df.paint_type.value_counts(dropna=False)

Metallic       9794
NaN            5772
Uni/basic       347
Perl effect       6
Name: paint_type, dtype: int64

In [940]:
def fill_most(df, group_col, col_name):
    #Fills the missing values with the most existing value (mode) in the relevant column according to single-stage grouping
    for group in list(df[group_col].unique()):
        cond = df[group_col] == group
        grp_inx = list(df[cond][col_name].index)
        mode = list(df[cond][col_name].mode())
        if mode != []:
            df[col_name].iloc[grp_inx] = df[col_name].iloc[grp_inx].fillna(
                df[cond][col_name].mode()[0])
        else:
            df[col_name].iloc[grp_inx] = df[col_name].iloc[grp_inx].fillna(
                df[col_name].mode()[0])
    print("Number of NaN : ", df[col_name].isnull().sum())
    print("------------------")
    print(df[col_name].value_counts(dropna=False))


In [941]:
for make_model in list(df["make_model"].unique()):
    cond = df["make_model"] == make_model
    # we are taking our make_model's most repeated paint_type and assigning it mode
    mode = list(df[cond]["paint_type"].mode())
    if mode != []:
        # filling our paint_type with most repeated paint type of our make_model
        df.loc[cond, "paint_type"] = df.loc[cond, "paint_type"].fillna(
            df[cond]["paint_type"].mode()[0])
    else:
        df.loc[cond, "paint_type"] = df.loc[cond,
                                           "paint_type"].fillna(df["paint_type"].mode()[0])


In [942]:
fill_most(df, "make_model", "paint_type")


Number of NaN :  0
------------------
Metallic       15549
Uni/basic        364
Perl effect        6
Name: paint_type, dtype: int64


In [943]:
df.paint_type.value_counts(dropna=False)

Metallic       15549
Uni/basic        364
Perl effect        6
Name: paint_type, dtype: int64

In [944]:
df.columns

Index(['make_model', 'body_type', 'price', 'vat', 'km', 'previous_owners',
       'next_inspection', 'inspection_new', 'paint_type', 'num_of_doors',
       'num_of_seats', 'gearing_type', 'cylinders', 'drive_chain', 'fuel',
       'consumption', 'co2_emission', 'emission_class', 'comfort_convenience',
       'entertainment_media', 'extras', 'safety_security', 'gears', 'age',
       'hp_kw', 'type', 'upholstery_type', 'upholstery_color',
       'displacement_cc', 'weight_kg', 'cons_comb', 'cons_city',
       'cons_country'],
      dtype='object')

### num_of_doors column:

In [945]:
print('\n''Percentage of Missing Values : %', round(
    df['num_of_doors'].isnull().sum()/df.shape[0]*100, 2))
print("Number of Missings           : ",
      df['num_of_doors'].isnull().sum())
print("Number of Uniques            : ", df['num_of_doors'].nunique())
print('Value counts                 : ''\n''\n',df['num_of_doors'].value_counts(dropna=False))


Percentage of Missing Values : % 1.33
Number of Missings           :  212
Number of Uniques            :  6
Value counts                 : 

 5.000    11575
4.000     3079
3.000      832
2.000      219
NaN        212
1.000        1
7.000        1
Name: num_of_doors, dtype: int64


In [946]:
df.groupby(["make_model", "body_type", "num_of_doors"])[
    ["make_model", "body_type", "num_of_doors"]].head()


make_model      body_type  num_of_doors
0             Audi A1         Sedans         5.000
1             Audi A1         Sedans         3.000
2             Audi A1         Sedans         4.000
3             Audi A1         Sedans         3.000
4             Audi A1         Sedans         5.000
...               ...            ...           ...
15652  Renault Espace  Station wagon         4.000
15805  Renault Espace        Compact         5.000
15851  Renault Espace  Station wagon         4.000
15884  Renault Espace  Station wagon         4.000
15905  Renault Espace        Compact         5.000

[328 rows x 3 columns]

In [947]:
df["num_of_doors"].fillna("-", inplace=True)


In [948]:
df.groupby(["make_model", "body_type", "num_of_doors"]).price.describe()


count      mean      std       min  \
make_model     body_type   num_of_doors                                        
Audi A1        Compact     2.0           69.000 15201.609 2121.071 10900.000   
                           3.0           80.000 15190.013 2353.692  9950.000   
                           4.0          207.000 19018.077 4481.635 10490.000   
                           5.0          666.000 20055.171 4463.177 11100.000   
                           -             17.000 22362.412 4836.261 12990.000   
...                                         ...       ...      ...       ...   
Renault Espace Transporter 5.0           52.000 22606.481 4226.833 14999.000   
               Van         4.0           90.000 28483.511 7594.880 12614.000   
                           5.0          711.000 31263.684 8816.686 13000.000   
                           7.0            1.000 21600.000      NaN 21600.000   
                           -              9.000 28456.556 7144.922 18999.000   

                                              25%       50%       75%  \
make_model     body_type   num_of_doors                                 
Audi A1        Compact     2.0          13990.000 15850.000 15850.000   
                           3.0          13837.500 14995.000 15912.500   
                           4.0          14990.000 18325.000 22320.000   
                           5.0          16445.000 19895.000 22690.000   
                           -            21390.000 21985.000 25490.000   
...                                           ...       ...       ...   
Renault Espace Transporter 5.0          19787.500 21000.000 25250.000   
               Van         4.0          25490.000 25490.000 31990.000   
                           5.0          24845.000 30480.000 35798.000   
                           7.0          21600.000 21600.000 21600.000   
                           -            21980.000 26880.000 34990.000   

                                              max  
make_model     body_type   num_of_doors            
Audi A1        Compact     2.0          23090.000  
                           3.0          21490.000  
                           4.0          28990.000  
                           5.0          31990.000  
                           -            29197.000  
...                                           ...  
Renault Espace Transporter 5.0          32700.000  
               Van         4.0          48990.000  
                           5.0          68320.000  
                           7.0          21600.000  
                           -            38890.000  

[108 rows x 8 columns]

In [949]:
df[df["make_model"] == "Renault Espace"]["num_of_doors"].mode()


0   5.000
Name: num_of_doors, dtype: object

In [950]:
df["num_of_doors"].replace("-", np.nan, inplace=True)


In [951]:
df.num_of_doors.value_counts(dropna=False)

5.000    11575
4.000     3079
3.000      832
2.000      219
NaN        212
1.000        1
7.000        1
Name: num_of_doors, dtype: int64

In [952]:
df.num_of_doors.replace([1, 7], np.nan, inplace=True)
df.num_of_doors.value_counts(dropna=False)

5.000    11575
4.000     3079
3.000      832
2.000      219
NaN        214
Name: num_of_doors, dtype: int64

In [953]:
# method can be \"mode\" or \"median\" or \"ffill\"
def fill(df, group_col1, group_col2, col_name, method):

#Fills the missing values based on selected method (mode/median/ffill) according to two-stage grouping
    if method == "mode":
        for group1 in list(df[group_col1].unique()):
            for group2 in list(df[group_col2].unique()):
                cond1 = df[group_col1] == group1
                cond2 = (df[group_col1] == group1) & (df[group_col2] == group2)
                grp_inx = list(df[cond2][col_name].index)
                mode1 = list(df[cond1][col_name].mode())
                mode2 = list(df[cond2][col_name].mode())
                if (mode1 != []) and (mode2 != []):
                    df[col_name].iloc[grp_inx] = df[col_name].iloc[grp_inx].fillna(
                        df[cond2][col_name].mode()[0]).fillna(df[cond1][col_name].mode()[0])
                elif mode1 != []:
                    df[col_name].iloc[grp_inx] = df[col_name].iloc[grp_inx].fillna(
                        df[cond1][col_name].mode()[0])
                else:
                    df[col_name].iloc[grp_inx] = df[col_name].iloc[grp_inx].fillna(
                        df[col_name].mode()[0])
    elif method == "median":
            for group1 in list(df[group_col1].unique()):
                for group2 in list(df[group_col2].unique()):
                    cond1 = df[group_col1] == group1
                    cond2 = (df[group_col1] == group1) & (
                        df[group_col2] == group2)
                    grp_inx = list(df[cond2][col_name].index)
                    df[col_name].iloc[grp_inx] = df[col_name].iloc[grp_inx].fillna(
                        df[cond2][col_name].median()).fillna(df[cond1][col_name].median()).fillna(df[col_name].median())

    elif method == "ffill":           
        for group1 in list(df[group_col1].unique()):
            for group2 in list(df[group_col2].unique()):
                cond1 = df[group_col1]==group1
                cond2 = (df[group_col1]==group1) & (df[group_col2]==group2)
                grp_inx = list(df[cond2][col_name].index)
                df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(method="ffill").fillna(method="bfill")
                    
        for group1 in list(df[group_col1].unique()):
            cond1 = df[group_col1]==group1
            df.loc[cond1, col_name] = df.loc[cond1, col_name].fillna(method="ffill").fillna(method="bfill")            
               
        df[col_name] = df[col_name].fillna(method="ffill").fillna(method="bfill")
        
    print("Number of NaN : ",df[col_name].isnull().sum())
    print("------------------")
    print(df[col_name].value_counts(dropna=False))

In [954]:
fill(df, "make_model", "body_type", "num_of_doors", "mode")


Number of NaN :  0
------------------
5.000    11789
4.000     3079
3.000      832
2.000      219
Name: num_of_doors, dtype: int64


In [955]:
df.columns

Index(['make_model', 'body_type', 'price', 'vat', 'km', 'previous_owners',
       'next_inspection', 'inspection_new', 'paint_type', 'num_of_doors',
       'num_of_seats', 'gearing_type', 'cylinders', 'drive_chain', 'fuel',
       'consumption', 'co2_emission', 'emission_class', 'comfort_convenience',
       'entertainment_media', 'extras', 'safety_security', 'gears', 'age',
       'hp_kw', 'type', 'upholstery_type', 'upholstery_color',
       'displacement_cc', 'weight_kg', 'cons_comb', 'cons_city',
       'cons_country'],
      dtype='object')

### num_of_seats column:

In [956]:
print('\n''Percentage of Missing Values : %', round(
    df['num_of_seats'].isnull().sum()/df.shape[0]*100, 2))
print("Number of Missings           : ",
      df['num_of_seats'].isnull().sum())
print("Number of Uniques            : ", df['num_of_seats'].nunique())
print('Value counts                 : ''\n''\n',df['num_of_seats'].value_counts(dropna=False))


Percentage of Missing Values : % 6.14
Number of Missings           :  977
Number of Uniques            :  6
Value counts                 : 

 5.000    13336
4.000     1125
NaN        977
7.000      362
2.000      116
6.000        2
3.000        1
Name: num_of_seats, dtype: int64


In [957]:
df.num_of_seats.replace([3, 6], np.nan, inplace=True)


In [958]:
df.num_of_seats.value_counts(dropna = False)

5.000    13336
4.000     1125
NaN        980
7.000      362
2.000      116
Name: num_of_seats, dtype: int64

In [959]:
fill(df, "make_model", "body_type", "num_of_seats", "mode")


Number of NaN :  0
------------------
5.000    14311
4.000     1127
7.000      362
2.000      119
Name: num_of_seats, dtype: int64


### gearing_type column:

In [960]:
print('\n''Percentage of Missing Values : %', round(
    df['gearing_type'].isnull().sum()/df.shape[0]*100, 2))
print("Number of Missings           : ",
      df['gearing_type'].isnull().sum())
print("Number of Uniques            : ", df['gearing_type'].nunique())
print('Value counts                 : ''\n''\n',df['gearing_type'].value_counts(dropna=False))


Percentage of Missing Values : % 0.0
Number of Missings           :  0
Number of Uniques            :  3
Value counts                 : 

 Manual            8153
Automatic         7297
Semi-automatic     469
Name: gearing_type, dtype: int64


There is no missing value in this column

### cylinders column

In [961]:
print('\n''Percentage of Missing Values : %', round(
    df['cylinders'].isnull().sum()/df.shape[0]*100, 2))
print("Number of Missings           : ",
      df['cylinders'].isnull().sum())
print("Number of Uniques            : ", df['cylinders'].nunique())
print('Value counts                 : ''\n''\n',df['cylinders'].value_counts(dropna=False))


Percentage of Missing Values : % 35.68
Number of Missings           :  5680
Number of Uniques            :  7
Value counts                 : 

 4.000    8105
NaN      5680
3.000    2104
5.000      22
6.000       3
8.000       2
2.000       2
1.000       1
Name: cylinders, dtype: int64


In [962]:
fill(df, "make_model", "body_type", "cylinders", "mode")


Number of NaN :  0
------------------
4.000    12926
3.000     2963
5.000       22
6.000        3
8.000        2
2.000        2
1.000        1
Name: cylinders, dtype: int64


### drive_chain column:

In [963]:
print('\n''Percentage of Missing Values : %', round(
    df['drive_chain'].isnull().sum()/df.shape[0]*100, 2))
print("Number of Missings           : ",
      df['drive_chain'].isnull().sum())
print("Number of Uniques            : ", df['drive_chain'].nunique())
print('Value counts                 : ''\n''\n',df['drive_chain'].value_counts(dropna=False))


Percentage of Missing Values : % 43.08
Number of Missings           :  6858
Number of Uniques            :  3
Value counts                 : 

 front    8886
NaN      6858
4WD       171
rear        4
Name: drive_chain, dtype: int64


In [964]:
df["drive_chain"].fillna("-", inplace=True)


In [965]:
df.groupby(["make_model", "body_type", "drive_chain"]).price.describe()


count      mean       std       min  \
make_model     body_type   drive_chain                                         
Audi A1        Compact     -           352.000 17620.869  4226.116 10490.000   
                           4WD           2.000 14790.000  1258.650 13900.000   
                           front       685.000 20008.223  4511.348  9950.000   
               Coupe       -             2.000 14925.000  1378.858 13950.000   
               Sedans      -           561.000 17830.440  4362.321  8999.000   
...                                        ...       ...       ...       ...   
Renault Espace Transporter 4WD           1.000 30000.000       NaN 30000.000   
                           front         6.000 23258.167  5973.317 17000.000   
               Van         -           394.000 29624.208  8543.180 12990.000   
                           4WD          38.000 38150.763 10013.779 24950.000   
                           front       379.000 31525.164  8343.192 12614.000   

                                             25%       50%       75%       max  
make_model     body_type   drive_chain                                          
Audi A1        Compact     -           14990.000 15900.000 20885.750 29190.000  
                           4WD         14345.000 14790.000 15235.000 15680.000  
                           front       16430.000 19890.000 22690.000 31990.000  
               Coupe       -           14437.500 14925.000 15412.500 15900.000  
               Sedans      -           14900.000 16490.000 20700.000 37900.000  
...                                          ...       ...       ...       ...  
Renault Espace Transporter 4WD         30000.000 30000.000 30000.000 30000.000  
                           front       19262.500 21500.000 26624.250 32700.000  
               Van         -           23990.000 27545.000 34368.750 63477.000  
                           4WD         31900.000 34200.000 45747.000 57990.000  
                           front       25050.000 31360.000 36151.000 68320.000  

[93 rows x 8 columns]

In [966]:
list(df.make_model.unique())

['Audi A1',
 'Audi A2',
 'Audi A3',
 'Opel Astra',
 'Opel Corsa',
 'Opel Insignia',
 'Renault Clio',
 'Renault Duster',
 'Renault Espace']

In [967]:
df[(df["make_model"] == "Renault Duster") & (df["body_type"] == "Off-Road")
   ][["make_model", "body_type", "drive_chain"]].sample(10)


make_model body_type drive_chain
14916  Renault Duster  Off-Road           -
14913  Renault Duster  Off-Road           -
14905  Renault Duster  Off-Road           -
14926  Renault Duster  Off-Road           -
14920  Renault Duster  Off-Road           -
14894  Renault Duster  Off-Road           -
14902  Renault Duster  Off-Road         4WD
14904  Renault Duster  Off-Road           -
14896  Renault Duster  Off-Road           -
14911  Renault Duster  Off-Road           -

In [968]:
off_road = (df['make_model'] == "Renault Duster") & (df["body_type"] == "Off-Road")


In [969]:
df.loc[off_road,'drive_chain'] = df.loc[off_road,'drive_chain'].replace('-','4WD')

In [970]:
df["drive_chain"].value_counts(dropna=False)


front    8886
-        6826
4WD       203
rear        4
Name: drive_chain, dtype: int64

In [971]:
df["drive_chain"] = df["drive_chain"].replace('-', np.nan)


In [972]:
df["drive_chain"].value_counts(dropna=False)


front    8886
NaN      6826
4WD       203
rear        4
Name: drive_chain, dtype: int64

In [973]:
fill(df, "make_model", "body_type", "drive_chain", "mode")


Number of NaN :  0
------------------
front    15711
4WD        204
rear         4
Name: drive_chain, dtype: int64


In [974]:
df["drive_chain"].value_counts(dropna=False)


front    15711
4WD        204
rear         4
Name: drive_chain, dtype: int64

In [975]:
df.columns

Index(['make_model', 'body_type', 'price', 'vat', 'km', 'previous_owners',
       'next_inspection', 'inspection_new', 'paint_type', 'num_of_doors',
       'num_of_seats', 'gearing_type', 'cylinders', 'drive_chain', 'fuel',
       'consumption', 'co2_emission', 'emission_class', 'comfort_convenience',
       'entertainment_media', 'extras', 'safety_security', 'gears', 'age',
       'hp_kw', 'type', 'upholstery_type', 'upholstery_color',
       'displacement_cc', 'weight_kg', 'cons_comb', 'cons_city',
       'cons_country'],
      dtype='object')

### fuel column:

In [976]:
print('\n''Percentage of Missing Values : %', round(
    df['fuel'].isnull().sum()/df.shape[0]*100, 2))
print("Number of Missings           : ",
      df['fuel'].isnull().sum())
print("Number of Uniques            : ", df['fuel'].nunique())
print('Value counts                 : ''\n''\n',df['fuel'].value_counts(dropna=False))


Percentage of Missing Values : % 0.0
Number of Missings           :  0
Number of Uniques            :  4
Value counts                 : 

 Benzine     8551
Diesel      7299
LPG/CNG       64
Electric       5
Name: fuel, dtype: int64


There is no missing value in this column

### co2_emission column:

In [977]:
print('\n''Percentage of Missing Values : %', round(
    df['co2_emission'].isnull().sum()/df.shape[0]*100, 2))
print("Number of Missings           : ",
      df['co2_emission'].isnull().sum())
print("Number of Uniques            : ", df['co2_emission'].nunique())
print('Value counts                 : ''\n''\n',df['co2_emission'].value_counts(dropna=False))


Percentage of Missing Values : % 15.3
Number of Missings           :  2436
Number of Uniques            :  120
Value counts                 : 

 NaN        2436
120.000     740
99.000      545
97.000      537
104.000     501
           ... 
990.000       1
12.324        1
1.060         1
51.000        1
193.000       1
Name: co2_emission, Length: 121, dtype: int64


In [978]:
df["co2_emission"].fillna("-", inplace=True)


In [979]:
df.groupby(["make_model", "body_type","co2_emission"]).price.describe()

count      mean      std       min  \
make_model     body_type co2_emission                                        
Audi A1        Compact   1.0            1.000 20881.000      NaN 20881.000   
                         9.0            1.000 12479.000      NaN 12479.000   
                         10.0         147.000 16946.871 2850.063  9950.000   
                         11.0          25.000 19960.360 2676.262 14930.000   
                         14.0           2.000 28750.000  268.701 28560.000   
...                                       ...       ...      ...       ...   
Renault Espace Van       188.0          1.000 43080.000      NaN 43080.000   
                         191.0          2.000 28465.000    0.000 28465.000   
                         193.0          1.000 38990.000      NaN 38990.000   
                         194.0          1.000 46490.000      NaN 46490.000   
                         -            209.000 31038.459 8711.241 12990.000   

                                            25%       50%       75%       max  
make_model     body_type co2_emission                                          
Audi A1        Compact   1.0          20881.000 20881.000 20881.000 20881.000  
                         9.0          12479.000 12479.000 12479.000 12479.000  
                         10.0         15765.000 16450.000 18333.000 29150.000  
                         11.0         17970.000 19990.000 21460.000 28980.000  
                         14.0         28655.000 28750.000 28845.000 28940.000  
...                                         ...       ...       ...       ...  
Renault Espace Van       188.0        43080.000 43080.000 43080.000 43080.000  
                         191.0        28465.000 28465.000 28465.000 28465.000  
                         193.0        38990.000 38990.000 38990.000 38990.000  
                         194.0        46490.000 46490.000 46490.000 46490.000  
                         -            24750.000 29990.000 34200.000 64332.000  

[760 rows x 8 columns]

In [980]:
df["co2_emission"].replace("-", np.nan, inplace=True)


In [981]:
fill(df, "make_model", "body_type", "co2_emission", "median")


Number of NaN :  0
------------------
120.000    836
104.000    679
106.000    674
114.000    556
99.000     546
          ... 
1.060        1
51.000       1
165.000      1
112.500      1
193.000      1
Name: co2_emission, Length: 123, dtype: int64


### emission_class column:

In [982]:
print('\n''Percentage of Missing Values : %', round(
    df['emission_class'].isnull().sum()/df.shape[0]*100, 2))
print("Number of Missings           : ",
      df['emission_class'].isnull().sum())
print("Number of Uniques            : ", df['emission_class'].nunique())
print('Value counts                 : ''\n''\n',df['emission_class'].value_counts(dropna=False))


Percentage of Missing Values : % 22.79
Number of Missings           :  3628
Number of Uniques            :  3
Value counts                 : 

 Euro 6    12173
NaN        3628
Euro 5       78
Euro 4       40
Name: emission_class, dtype: int64


In [983]:
df["emission_class"].fillna("-", inplace=True)


In [984]:
df["emission_class"].value_counts(dropna=False)


Euro 6    12173
-          3628
Euro 5       78
Euro 4       40
Name: emission_class, dtype: int64

In [985]:
df.groupby(["age", "fuel", "emission_class"]).price.describe()


count      mean       std       min  \
age   fuel     emission_class                                          
0.000 Benzine  -              1024.000 21933.499  8305.713   331.000   
               Euro 4           33.000 13377.364  1586.304 10900.000   
               Euro 5            1.000 17600.000       NaN 17600.000   
               Euro 6         2428.000 21459.133  8290.596   120.000   
      Diesel   -               335.000 27596.591  7964.355  6950.000   
               Euro 6          595.000 29233.887  7930.018  8800.000   
      LPG/CNG  -                 3.000 18516.667 10017.027  6950.000   
               Euro 6           16.000 18689.188 10338.898  6950.000   
1.000 Benzine  -               571.000 17204.217  5212.353  7990.000   
               Euro 4            3.000 18846.667 14644.044 10000.000   
               Euro 5            6.000 14923.000  3808.072  8950.000   
               Euro 6         2047.000 17001.402  6457.753    13.000   
      Diesel   -               308.000 21673.812  6841.475  8990.000   
               Euro 5            2.000 18650.000  2616.295 16800.000   
               Euro 6         1584.000 20170.714  4727.402   255.000   
      Electric Euro 6            3.000 37449.667  1361.635 35899.000   
      LPG/CNG  Euro 6            4.000  9975.000   411.299  9500.000   
2.000 Benzine  -               259.000 13948.297  4924.363  6950.000   
               Euro 4            1.000  9400.000       NaN  9400.000   
               Euro 5            9.000 13793.222  7595.497  7900.000   
               Euro 6         1043.000 14595.511  5602.112  6499.000   
      Diesel   -               380.000 16160.658  5624.031  6900.000   
               Euro 5            7.000 12125.714   748.751 11700.000   
               Euro 6         1561.000 16427.623  4782.605  6000.000   
      LPG/CNG  -                 6.000  9375.667  1752.931  7990.000   
               Euro 6           11.000 16654.545  7014.893  8500.000   
3.000 Benzine  -               236.000 12406.089  3795.139  6290.000   
               Euro 4            1.000 12990.000       NaN 12990.000   
               Euro 5           12.000 10530.667  3138.381  5970.000   
               Euro 6          877.000 12744.804  4336.588  4990.000   
      Diesel   -               500.000 12998.596  4969.636  5490.000   
               Euro 4            2.000 12925.000  1308.148 12000.000   
               Euro 5           40.000 12138.250  4224.752  7000.000   
               Euro 6         1985.000 14345.886  4269.198  4950.000   
      Electric -                 1.000  8490.000       NaN  8490.000   
               Euro 6            1.000 24950.000       NaN 24950.000   
      LPG/CNG  -                 5.000 18220.000   156.525 18150.000   
               Euro 5            1.000  7500.000       NaN  7500.000   
               Euro 6           18.000 17472.167  4495.842  7000.000   

                                    25%       50%       75%       max  
age   fuel     emission_class                                          
0.000 Benzine  -              16390.000 21900.000 26300.000 64332.000  
               Euro 4         12250.000 13250.000 14477.000 16033.000  
               Euro 5         17600.000 17600.000 17600.000 17600.000  
               Euro 6         14996.750 21839.500 26488.500 63900.000  
      Diesel   -              23605.500 26300.000 31990.000 56950.000  
               Euro 6         23965.000 26998.000 34777.500 68320.000  
      LPG/CNG  -              15625.000 24300.000 24300.000 24300.000  
               Euro 6         10687.500 14949.500 26900.000 34738.000  
1.000 Benzine  -              13980.000 16890.000 20900.000 39959.000  
               Euro 4         10395.000 10790.000 23270.000 35750.000  
               Euro 5         13400.000 15250.000 16800.000 19988.000  
               Euro 6         12965.000 16350.000 20480.000 74600.000  
      Diesel   -              16265.000 20985.000 24492.500 38990.000  


In [986]:
df.groupby(["age","fuel","emission_class"])["age","fuel","emission_class"].head()

age     fuel emission_class
0     3.000   Diesel         Euro 6
1     2.000  Benzine         Euro 6
2     3.000   Diesel         Euro 6
3     3.000   Diesel         Euro 6
4     3.000   Diesel         Euro 6
...     ...      ...            ...
14894 0.000  Benzine         Euro 4
14895 0.000  Benzine         Euro 4
14896 0.000  Benzine         Euro 4
14897 0.000  Benzine         Euro 4
15779 1.000  Benzine         Euro 4

[158 rows x 3 columns]

In [987]:
df["emission_class"].replace("-", np.nan, inplace=True)


In [988]:
df["emission_class"].value_counts(dropna=False)


Euro 6    12173
NaN        3628
Euro 5       78
Euro 4       40
Name: emission_class, dtype: int64

In [989]:
df['emission_class'].fillna(df.groupby(["age", "fuel"], as_index=True)[
    "emission_class"].transform(lambda x: pd.Series.mode(x)[0]), inplace=True)


In [990]:
df["emission_class"].value_counts(dropna=False)


Euro 6    15801
Euro 5       78
Euro 4       40
Name: emission_class, dtype: int64

In [991]:
df.columns

Index(['make_model', 'body_type', 'price', 'vat', 'km', 'previous_owners',
       'next_inspection', 'inspection_new', 'paint_type', 'num_of_doors',
       'num_of_seats', 'gearing_type', 'cylinders', 'drive_chain', 'fuel',
       'consumption', 'co2_emission', 'emission_class', 'comfort_convenience',
       'entertainment_media', 'extras', 'safety_security', 'gears', 'age',
       'hp_kw', 'type', 'upholstery_type', 'upholstery_color',
       'displacement_cc', 'weight_kg', 'cons_comb', 'cons_city',
       'cons_country'],
      dtype='object')

### comfort_convenience column:

In [992]:
print('\n''Percentage of Missing Values : %', round(
    df['comfort_convenience'].isnull().sum()/df.shape[0]*100, 2))
print("Number of Missings           : ",
      df['comfort_convenience'].isnull().sum())
print("Number of Uniques            : ", df['comfort_convenience'].nunique())
print('Value counts                 : ''\n''\n',df['comfort_convenience'].value_counts(dropna=False))


Percentage of Missing Values : % 5.78
Number of Missings           :  920
Number of Uniques            :  6198
Value counts                 : 

 NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        920
Air conditioning, Electrical side mirrors, Hill Holder, Power windows                                                                                                                                                                                                                                                                                  

In [993]:
list(df.body_type.unique())

['Sedans',
 'Station wagon',
 'Compact',
 'Coupe',
 'Van',
 'Off-Road',
 'Convertible',
 'Transporter']

In [994]:
list(df.make_model.unique())


['Audi A1',
 'Audi A2',
 'Audi A3',
 'Opel Astra',
 'Opel Corsa',
 'Opel Insignia',
 'Renault Clio',
 'Renault Duster',
 'Renault Espace']

In [995]:
df['comfort_convenience'].fillna(df.groupby(["make_model", "body_type"], as_index=True)[
    "comfort_convenience"].transform(lambda x: pd.Series.mode(x)[0]), inplace=True)


In [996]:
df.comfort_convenience.value_counts(dropna=False)

Air conditioning, Electrical side mirrors, Hill Holder, Power windows                                                                                                                                                                                                                                                                                                                                                                                                                                                      388
Air conditioning, Armrest, Automatic climate control, Cruise control, Electrical side mirrors, Leather steering wheel, Light sensor, Lumbar support, Multi-function steering wheel, Navigation system, Park Distance Control, Parking assist system sensors front, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Start-stop system                                                                                                                                       

### entertainment_media column:

In [997]:
print('\n''Percentage of Missing Values : %', round(
    df['entertainment_media'].isnull().sum()/df.shape[0]*100, 2))
print("Number of Missings           : ",
      df['entertainment_media'].isnull().sum())
print("Number of Uniques            : ", df['entertainment_media'].nunique())
print('Value counts                 : ''\n''\n',df['entertainment_media'].value_counts(dropna=False))


Percentage of Missing Values : % 8.63
Number of Missings           :  1374
Number of Uniques            :  346
Value counts                 : 

 NaN                                                                                                         1374
Bluetooth, Hands-free equipment, On-board computer, Radio, USB                                              1282
Bluetooth, Hands-free equipment, MP3, On-board computer, Radio, USB                                          982
Bluetooth, CD player, Hands-free equipment, MP3, On-board computer, Radio, USB                               783
On-board computer, Radio                                                                                     487
                                                                                                            ... 
Bluetooth, CD player, Digital radio, Hands-free equipment, Radio                                               1
CD player, Hands-free equipment, MP3, Radio, USB               

In [998]:
fill(df, "make_model", "body_type", "entertainment_media", "mode")

Number of NaN :  0
------------------
Bluetooth, Hands-free equipment, On-board computer, Radio, USB                         1738
Bluetooth, Hands-free equipment, MP3, On-board computer, Radio, USB                    1134
Bluetooth, CD player, Hands-free equipment, MP3, On-board computer, Radio, USB         1010
On-board computer                                                                       615
Radio                                                                                   558
                                                                                       ... 
Bluetooth, CD player, MP3                                                                 1
CD player, USB                                                                            1
Bluetooth, CD player, Digital radio, Radio, USB                                           1
Bluetooth, CD player, Digital radio, MP3, On-board computer, Radio, Television, USB       1
Hands-free equipment, On-board computer, R

### extras column:

In [999]:
print('\n''Percentage of Missing Values : %', round(
    df['extras'].isnull().sum()/df.shape[0]*100, 2))
print("Number of Missings           : ",
      df['extras'].isnull().sum())
print("Number of Uniques            : ", df['extras'].nunique())
print('Value counts                 : ''\n''\n',df['extras'].value_counts(dropna=False))


Percentage of Missing Values : % 18.61
Number of Missings           :  2962
Number of Uniques            :  659
Value counts                 : 

 Alloy wheels                                                                                                     3245
NaN                                                                                                              2962
Alloy wheels, Touch screen                                                                                        697
Alloy wheels, Voice Control                                                                                       577
Alloy wheels, Touch screen, Voice Control                                                                         541
                                                                                                                 ... 
Alloy wheels, Catalytic Converter, Shift paddles, Sport package, Sport seats, Sport suspension, Voice Control       1
Alloy wheels, Catalytic Con

In [1000]:
#df['extras'].fillna(df.groupby(["make_model", "body_type"], as_index=True)["extras"].transform(lambda x: pd.Series.mode(x)), inplace=True)
# It doesn't work for some columns!!!

In [1001]:
fill(df, "make_model", "body_type", "extras", "mode")


Number of NaN :  0
------------------
Alloy wheels                                                                                                     5786
Alloy wheels, Touch screen                                                                                        697
Roof rack                                                                                                         596
Alloy wheels, Voice Control                                                                                       582
Alloy wheels, Touch screen, Voice Control                                                                         544
                                                                                                                 ... 
Alloy wheels, Catalytic Converter, Shift paddles, Sport package, Sport seats, Sport suspension, Voice Control       1
Alloy wheels, Catalytic Converter, Roof rack, Sport package, Sport seats, Trailer hitch                             1
Alloy wheels, Cata

In [1002]:
df.extras.value_counts(dropna=False)

Alloy wheels                                                                                                     5786
Alloy wheels, Touch screen                                                                                        697
Roof rack                                                                                                         596
Alloy wheels, Voice Control                                                                                       582
Alloy wheels, Touch screen, Voice Control                                                                         544
                                                                                                                 ... 
Alloy wheels, Catalytic Converter, Shift paddles, Sport package, Sport seats, Sport suspension, Voice Control       1
Alloy wheels, Catalytic Converter, Roof rack, Sport package, Sport seats, Trailer hitch                             1
Alloy wheels, Catalytic Converter, Ski bag, Sport packag

In [1003]:
df.columns

Index(['make_model', 'body_type', 'price', 'vat', 'km', 'previous_owners',
       'next_inspection', 'inspection_new', 'paint_type', 'num_of_doors',
       'num_of_seats', 'gearing_type', 'cylinders', 'drive_chain', 'fuel',
       'consumption', 'co2_emission', 'emission_class', 'comfort_convenience',
       'entertainment_media', 'extras', 'safety_security', 'gears', 'age',
       'hp_kw', 'type', 'upholstery_type', 'upholstery_color',
       'displacement_cc', 'weight_kg', 'cons_comb', 'cons_city',
       'cons_country'],
      dtype='object')

### safety_security column:

In [1004]:
print('\n''Percentage of Missing Values : %', round(
    df['safety_security'].isnull().sum()/df.shape[0]*100, 2))
print("Number of Missings           : ",
      df['safety_security'].isnull().sum())
print("Number of Uniques            : ", df['safety_security'].nunique())
print('Value counts                 : ''\n''\n',df['safety_security'].value_counts(dropna=False))


Percentage of Missing Values : % 6.17
Number of Missings           :  982
Number of Uniques            :  4443
Value counts                 : 

 NaN                                                                                                                                                                                                                                                                                                                                                                                982
ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Fog lights, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control                                                                                                                                           538
ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Immobi

In [1005]:
df['safety_security'].fillna(df.groupby(["make_model", "body_type"], as_index=True)[
    "safety_security"].transform(lambda x: pd.Series.mode(x)[0]), inplace=True)
# hier this code works!!

In [1006]:
df.safety_security.value_counts(dropna=False)

ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Fog lights, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control                                                                                                                                           729
ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control                                                                                                                                                       480
ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Fog lights, Immobilizer, Isofix, LED Daytime Running Lights, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Tracti

In [1007]:
df.columns

Index(['make_model', 'body_type', 'price', 'vat', 'km', 'previous_owners',
       'next_inspection', 'inspection_new', 'paint_type', 'num_of_doors',
       'num_of_seats', 'gearing_type', 'cylinders', 'drive_chain', 'fuel',
       'consumption', 'co2_emission', 'emission_class', 'comfort_convenience',
       'entertainment_media', 'extras', 'safety_security', 'gears', 'age',
       'hp_kw', 'type', 'upholstery_type', 'upholstery_color',
       'displacement_cc', 'weight_kg', 'cons_comb', 'cons_city',
       'cons_country'],
      dtype='object')

### gears column:

In [1008]:
print('\n''Percentage of Missing Values : %', round(
    df['gears'].isnull().sum()/df.shape[0]*100, 2))
print("Number of Missings           : ",
      df['gears'].isnull().sum())
print("Number of Uniques            : ", df['gears'].nunique())
print('Value counts                 : ''\n''\n',df['gears'].value_counts(dropna=False))


Percentage of Missing Values : % 29.6
Number of Missings           :  4712
Number of Uniques            :  10
Value counts                 : 

 6.000     5822
NaN       4712
5.000     3239
7.000     1908
8.000      224
9.000        6
1.000        2
3.000        2
4.000        2
2.000        1
50.000       1
Name: gears, dtype: int64


In [1009]:
df["gears"].fillna("-", inplace=True)


In [1010]:
df["gears"].value_counts(dropna=False)


6.0     5822
-       4712
5.0     3239
7.0     1908
8.0      224
9.0        6
1.0        2
3.0        2
4.0        2
2.0        1
50.0       1
Name: gears, dtype: int64

In [1011]:
df.groupby(["make_model", "body_type", "gearing_type", "gears"]).price.describe()


count      mean       std  \
make_model     body_type gearing_type   gears                               
Audi A1        Compact   Automatic      5.0     3.000 22184.333  3421.302   
                                        6.0     6.000 21038.333  4282.039   
                                        7.0   199.000 22059.251  3918.116   
                                        8.0     1.000 16880.000       NaN   
                                        -     253.000 21640.427  4965.500   
...                                               ...       ...       ...   
Renault Espace Van       Manual         7.0     1.000 36590.000       NaN   
                                        -      14.000 27123.214  8657.066   
                         Semi-automatic 6.0    11.000 28885.455 11439.110   
                                        7.0     1.000 19900.000       NaN   
                                        -       4.000 26445.000  4549.289   

                                                    min       25%       50%  \
make_model     body_type gearing_type   gears                                 
Audi A1        Compact   Automatic      5.0   18497.000 20648.500 22800.000   
                                        6.0   16430.000 18725.000 20920.000   
                                        7.0   13990.000 18970.000 21790.000   
                                        8.0   16880.000 16880.000 16880.000   
                                        -     13880.000 16975.000 20950.000   
...                                                 ...       ...       ...   
Renault Espace Van       Manual         7.0   36590.000 36590.000 36590.000   
                                        -     16480.000 19623.000 25740.000   
                         Semi-automatic 6.0   16900.000 21450.000 24900.000   
                                        7.0   19900.000 19900.000 19900.000   
                                        -     22900.000 23650.000 24945.000   

                                                    75%       max  
make_model     body_type gearing_type   gears                      
Audi A1        Compact   Automatic      5.0   24028.000 25256.000  
                                        6.0   21060.000 28860.000  
                                        7.0   24365.000 29181.000  
                                        8.0   16880.000 16880.000  
                                        -     26980.000 29197.000  
...                                                 ...       ...  
Renault Espace Van       Manual         7.0   36590.000 36590.000  
                                        -     32625.000 43080.000  
                         Semi-automatic 6.0   32750.000 56950.000  
                                        7.0   19900.000 19900.000  
                                        -     27740.000 32990.000  

[215 rows x 8 columns]

In [1012]:
df.groupby(["make_model", "body_type", "gearing_type", "gears"])[
    ["make_model", "body_type", "gearing_type", "gears"]].head()


make_model body_type gearing_type gears
0             Audi A1    Sedans    Automatic     -
1             Audi A1    Sedans    Automatic 7.000
2             Audi A1    Sedans    Automatic     -
3             Audi A1    Sedans    Automatic 6.000
4             Audi A1    Sedans    Automatic     -
...               ...       ...          ...   ...
15824  Renault Espace       Van    Automatic 9.000
15827  Renault Espace       Van    Automatic 9.000
15845  Renault Espace       Van    Automatic 3.000
15869  Renault Espace       Van    Automatic 9.000
15905  Renault Espace   Compact    Automatic     -

[750 rows x 4 columns]

I think that these values were entered incorrectly, assuming that there will be no vehicles with 1, 2, 3, 4 and 50 gears.

In [1013]:
df["gears"].replace([1,2,3,4,50,"-"], np.nan, inplace=True)

In [1014]:
df["gears"].value_counts(dropna=False)


6.000    5822
NaN      4720
5.000    3239
7.000    1908
8.000     224
9.000       6
Name: gears, dtype: int64

In [1015]:
df['gears'].fillna(df.groupby(["make_model", "body_type", "gearing_type"], as_index=True)["gears"].transform(lambda x: pd.Series.mode(x)), inplace=True)


In [1016]:
df["gears"].value_counts(dropna=False)


6.000    5822
NaN      4719
5.000    3239
7.000    1909
8.000     224
9.000       6
Name: gears, dtype: int64

In [1017]:
list(df.make_model.unique())

['Audi A1',
 'Audi A2',
 'Audi A3',
 'Opel Astra',
 'Opel Corsa',
 'Opel Insignia',
 'Renault Clio',
 'Renault Duster',
 'Renault Espace']

In [1018]:
list(df.gearing_type.unique())

['Automatic', 'Manual', 'Semi-automatic']

In [1019]:
list(df.body_type.unique())


['Sedans',
 'Station wagon',
 'Compact',
 'Coupe',
 'Van',
 'Off-Road',
 'Convertible',
 'Transporter']

In [1020]:
df[(df["make_model"]=="Renault Clio") & (df["body_type"]=="Sedans")]["gears"].mode()

0   5.000
Name: gears, dtype: float64

In [1021]:
df[(df["body_type"]=="Sedans")]["gears"].mode()

0   6.000
Name: gears, dtype: float64

In [1022]:
df[(df["make_model"]=="Renault Clio") & (df["body_type"]=="Compact")]["gears"].mode()

0   5.000
Name: gears, dtype: float64

In [1023]:
df[(df["body_type"]=="Compact")]["gears"].mode()

0   5.000
Name: gears, dtype: float64

In [1024]:
df[(df["make_model"]=="Renault Clio") & (df["body_type"]=="Off-Road")]["gears"].mode()

0   5.000
1   6.000
Name: gears, dtype: float64

In [1025]:
df[(df["body_type"]=="Off-Road")]["gears"].mode()

0   6.000
Name: gears, dtype: float64

In [1026]:
df[(df["make_model"]=="Renault Clio") & (df["body_type"]=="Coupe")]["gears"].mode()

0   6.000
Name: gears, dtype: float64

In [1027]:
df[(df["body_type"]=="Coupe")]["gears"].mode()

0   5.000
Name: gears, dtype: float64

In [1028]:
df[(df["make_model"]=="Renault Clio") & (df["gearing_type"]=="Automatic")][["make_model", "body_type", "gearing_type", "gears"]].head()

make_model      body_type gearing_type  gears
13055  Renault Clio        Compact    Automatic    NaN
13056  Renault Clio  Station wagon    Automatic  6.000
13057  Renault Clio         Sedans    Automatic  6.000
13058  Renault Clio  Station wagon    Automatic  6.000
13059  Renault Clio         Sedans    Automatic    NaN

In [1029]:
df['gears'].fillna(df.groupby(["body_type", "gearing_type"], as_index=True)[
                   "gears"].transform(lambda x: pd.Series.mode(x)[0]), inplace=True)


In [1030]:
df["gears"].value_counts(dropna=False)


6.000    8054
5.000    4748
7.000    2887
8.000     224
9.000       6
Name: gears, dtype: int64

In [1031]:
df.columns

Index(['make_model', 'body_type', 'price', 'vat', 'km', 'previous_owners',
       'next_inspection', 'inspection_new', 'paint_type', 'num_of_doors',
       'num_of_seats', 'gearing_type', 'cylinders', 'drive_chain', 'fuel',
       'consumption', 'co2_emission', 'emission_class', 'comfort_convenience',
       'entertainment_media', 'extras', 'safety_security', 'gears', 'age',
       'hp_kw', 'type', 'upholstery_type', 'upholstery_color',
       'displacement_cc', 'weight_kg', 'cons_comb', 'cons_city',
       'cons_country'],
      dtype='object')

### hp_kw column:

In [1032]:
print('\n''Percentage of Missing Values : %', round(
    df['hp_kw'].isnull().sum()/df.shape[0]*100, 2))
print("Number of Missings           : ",
      df['hp_kw'].isnull().sum())
print("Number of Uniques            : ", df['hp_kw'].nunique())
print('Value counts                 : ''\n''\n',df['hp_kw'].value_counts(dropna=False))


Percentage of Missing Values : % 0.55
Number of Missings           :  88
Number of Uniques            :  80
Value counts                 : 

 85.000     2542
66.000     2122
81.000     1402
100.000    1308
110.000    1112
           ... 
84.000        1
195.000       1
44.000        1
239.000       1
9.000         1
Name: hp_kw, Length: 81, dtype: int64


In [1033]:
df["hp_kw"].fillna("-", inplace=True)


In [1034]:
df.groupby(["make_model", "body_type","hp_kw"]).price.describe()

count      mean      std       min       25%  \
make_model     body_type hp_kw                                                  
Audi A1        Compact   60.0   58.000 15189.828 1663.611 10900.000 14390.000   
                         66.0  162.000 15398.210 1934.301 10490.000 14042.500   
                         70.0  332.000 17983.262 3315.814  9950.000 15480.000   
                         71.0   32.000 20831.594 2410.840 15890.000 18937.500   
                         85.0  330.000 22604.103 4572.568 11100.000 19700.000   
...                                ...       ...      ...       ...       ...   
Renault Espace Van       150.0   1.000 43545.000      NaN 43545.000 43545.000   
                         165.0 175.000 38205.960 7911.485 26800.000 31990.000   
                         167.0   2.000 37990.000 2828.427 35990.000 36990.000   
                         168.0   3.000 38410.000 1712.659 36590.000 37620.000   
                         -      34.000 28466.029 4898.732 17990.000 24515.000   

                                     50%       75%       max  
make_model     body_type hp_kw                                
Audi A1        Compact   60.0  15774.500 16345.000 16978.000  
                         66.0  15465.000 16445.000 23700.000  
                         70.0  17447.000 21190.000 28990.000  
                         71.0  21425.000 22462.250 25256.000  
                         85.0  22497.000 26980.000 31990.000  
...                                  ...       ...       ...  
Renault Espace Van       150.0 43545.000 43545.000 43545.000  
                         165.0 35989.000 40999.000 64332.000  
                         167.0 37990.000 38990.000 39990.000  
                         168.0 38650.000 39320.000 39990.000  
                         -     28195.000 32900.000 39990.000  

[311 rows x 8 columns]

In [1035]:
df["hp_kw"].replace("-", np.nan, inplace=True)


In [1036]:
df['hp_kw'].fillna(df.groupby(["make_model", "body_type"], as_index=True)[
                   "hp_kw"].transform(lambda x: pd.Series.mode(x)[0]), inplace=True)


In [1037]:
df.hp_kw.value_counts(dropna=False)

85.000     2543
66.000     2124
81.000     1403
100.000    1314
110.000    1113
           ... 
123.000       1
44.000        1
195.000       1
75.000        1
9.000         1
Name: hp_kw, Length: 80, dtype: int64

In [1038]:
df.hp_kw.isnull().sum()

0

### type column:

In [1039]:
print('\n''Percentage of Missing Values : %', round(df['type'].isnull().sum()/df.shape[0]*100, 2))
print("Number of Missings           : ",
      df['type'].isnull().sum())
print("Number of Uniques            : ", df['type'].nunique())
print('Value counts                 : ''\n''\n',df['type'].value_counts(dropna=False))


Percentage of Missing Values : % 0.01
Number of Missings           :  2
Number of Uniques            :  5
Value counts                 : 

 Used              11096
New                1650
Pre-registered     1364
Employee's car     1011
Demonstration       796
NaN                   2
Name: type, dtype: int64


In [1040]:
df['type'].fillna(df.groupby(["make_model", "age"], as_index=True)[
    "type"].transform(lambda x: pd.Series.mode(x)[0]), inplace=True)


In [1041]:
df.type.value_counts(dropna=False)

Used              11097
New                1651
Pre-registered     1364
Employee's car     1011
Demonstration       796
Name: type, dtype: int64

### upholstery_type column:

In [1042]:
print('\n''Percentage of Missing Values : %', round(df['upholstery_type'].isnull().sum()/df.shape[0]*100, 2))
print("Number of Missings           : ",
      df['upholstery_type'].isnull().sum())
print("Number of Uniques            : ", df['upholstery_type'].nunique())
print('Value counts                 : ''\n''\n',df['upholstery_type'].value_counts(dropna=False))


Percentage of Missing Values : % 30.6
Number of Missings           :  4871
Number of Uniques            :  5
Value counts                 : 

 Cloth           8423
NaN             4871
Part leather    1499
Full leather    1009
Velour            60
alcantara         57
Name: upholstery_type, dtype: int64


In [1043]:
df.groupby(["make_model", "body_type", "upholstery_type"])["make_model", "body_type", "upholstery_type"].head()


make_model      body_type upholstery_type
0             Audi A1         Sedans           Cloth
1             Audi A1         Sedans           Cloth
2             Audi A1         Sedans           Cloth
4             Audi A1         Sedans           Cloth
5             Audi A1         Sedans    Part leather
...               ...            ...             ...
15650  Renault Espace            Van       alcantara
15652  Renault Espace  Station wagon    Part leather
15662  Renault Espace         Sedans    Full leather
15880  Renault Espace         Sedans    Full leather
15905  Renault Espace        Compact           Cloth

[403 rows x 3 columns]

In [1044]:
fill(df, "make_model", "body_type", "upholstery_type", "ffill")


Number of NaN :  0
------------------
Cloth           12157
Part leather     2128
Full leather     1458
alcantara          95
Velour             81
Name: upholstery_type, dtype: int64


### upholstery_color column:

In [1045]:
print('\n''Percentage of Missing Values : %', round(df['upholstery_color'].isnull().sum()/df.shape[0]*100, 2))
print("Number of Missings           : ",
      df['upholstery_color'].isnull().sum())
print("Number of Uniques            : ", df['upholstery_color'].nunique())
print('Value counts                 : ''\n''\n',df['upholstery_color'].value_counts(dropna=False))


Percentage of Missing Values : % 31.9
Number of Missings           :  5078
Number of Uniques            :  10
Value counts                 : 

 Black     8201
NaN       5078
Grey      1376
Other      960
Brown      207
Beige       54
Blue        16
White       13
Red          9
Yellow       4
Orange       1
Name: upholstery_color, dtype: int64


In [1046]:
df.upholstery_color.replace('Other', np.nan, inplace=True)

In [1047]:
fill(df, "make_model", "body_type", "upholstery_color", "ffill")


Number of NaN :  0
------------------
Black     13035
Grey       2228
Brown       488
Beige        80
White        34
Blue         29
Red          18
Yellow        6
Orange        1
Name: upholstery_color, dtype: int64


In [1048]:
df.columns

Index(['make_model', 'body_type', 'price', 'vat', 'km', 'previous_owners',
       'next_inspection', 'inspection_new', 'paint_type', 'num_of_doors',
       'num_of_seats', 'gearing_type', 'cylinders', 'drive_chain', 'fuel',
       'consumption', 'co2_emission', 'emission_class', 'comfort_convenience',
       'entertainment_media', 'extras', 'safety_security', 'gears', 'age',
       'hp_kw', 'type', 'upholstery_type', 'upholstery_color',
       'displacement_cc', 'weight_kg', 'cons_comb', 'cons_city',
       'cons_country'],
      dtype='object')

### displacement_cc column:

In [1049]:
print('\n''Percentage of Missing Values : %', round(
    df['displacement_cc'].isnull().sum()/df.shape[0]*100, 2))
print("Number of Missings           : ",
      df['displacement_cc'].isnull().sum())
print("Number of Uniques            : ", df['displacement_cc'].nunique())
print('Value counts                 : ''\n''\n',df['displacement_cc'].value_counts(dropna=False))


Percentage of Missing Values : % 3.12
Number of Missings           :  496
Number of Uniques            :  77
Value counts                 : 

 1598.000    4761
999.000     2438
1398.000    1314
1399.000     749
1229.000     677
            ... 
122.000        1
1198.000       1
1195.000       1
2967.000       1
1800.000       1
Name: displacement_cc, Length: 78, dtype: int64


In [1050]:
df["displacement_cc"].fillna("-", inplace=True)

In [1051]:
df.groupby(["make_model", "body_type","displacement_cc"]).price.describe()

count      mean      std       min  \
make_model     body_type displacement_cc                                        
Audi A1        Compact   929.0             5.000 16364.000 1504.819 14980.000   
                         995.0             2.000 21990.000 1414.214 20990.000   
                         999.0           663.000 20294.101 4570.798  9950.000   
                         1000.0            7.000 19498.429 5396.196 13500.000   
                         1395.0           98.000 18246.622 3084.081 12550.000   
...                                          ...       ...      ...       ...   
Renault Espace Van       1798.0          174.000 38173.299 7873.214 26800.000   
                         1800.0            1.000 50750.000      NaN 50750.000   
                         1997.0           92.000 39621.424 7514.270 12990.000   
                         2000.0            1.000 21900.000      NaN 21900.000   
                         -                77.000 28619.610 5732.766 17500.000   

                                               25%       50%       75%  \
make_model     body_type displacement_cc                                 
Audi A1        Compact   929.0           15480.000 16240.000 16240.000   
                         995.0           21490.000 21990.000 22490.000   
                         999.0           16480.000 20380.000 22820.000   
                         1000.0          16024.500 16800.000 22695.000   
                         1395.0          15850.000 17835.000 20900.000   
...                                            ...       ...       ...   
Renault Espace Van       1798.0          31990.000 35990.000 40991.750   
                         1800.0          50750.000 50750.000 50750.000   
                         1997.0          32975.000 39625.000 46262.500   
                         2000.0          21900.000 21900.000 21900.000   
                         -               24490.000 28465.000 32935.000   

                                               max  
make_model     body_type displacement_cc            
Audi A1        Compact   929.0           18880.000  
                         995.0           22990.000  
                         999.0           31990.000  
                         1000.0          28750.000  
                         1395.0          28880.000  
...                                            ...  
Renault Espace Van       1798.0          64332.000  
                         1800.0          50750.000  
                         1997.0          56950.000  
                         2000.0          21900.000  
                         -               44500.000  

[289 rows x 8 columns]

In [1052]:
df["displacement_cc"].replace("-", np.nan, inplace=True)


In [1053]:
fill(df, "make_model", "body_type", "displacement_cc", "mode")

Number of NaN :  0
------------------
1598.000    5044
999.000     2467
1398.000    1387
1399.000     768
1229.000     678
            ... 
122.000        1
1198.000       1
1195.000       1
2967.000       1
1800.000       1
Name: displacement_cc, Length: 77, dtype: int64


### weight_kg column:

In [1054]:
print('\n''Percentage of Missing Values : %', round(
    df['weight_kg'].isnull().sum()/df.shape[0]*100, 2))
print("Number of Missings           : ",
      df['weight_kg'].isnull().sum())
print("Number of Uniques            : ", df['weight_kg'].nunique())
print('Value counts                 : ''\n''\n',df['weight_kg'].value_counts(dropna=False))


Percentage of Missing Values : % 43.81
Number of Missings           :  6974
Number of Uniques            :  434
Value counts                 : 

 NaN         6974
1163.000     574
1360.000     356
1165.000     301
1335.000     242
            ... 
1960.000       1
1258.000       1
1167.000       1
1331.000       1
2037.000       1
Name: weight_kg, Length: 435, dtype: int64


In [1055]:
df["weight_kg"].sort_values().head(10)


8355      1.000
12779     1.000
1143    102.000
8857    840.000
14313   900.000
13513   977.000
13555   977.000
14479   980.000
14654   980.000
13609   980.000
Name: weight_kg, dtype: float64

In [1056]:
df["weight_kg"].replace([1, 102], np.nan, inplace=True)


In [1057]:
df.weight_kg.value_counts(dropna=False)

NaN         6977
1163.000     574
1360.000     356
1165.000     301
1335.000     242
            ... 
1258.000       1
1167.000       1
1331.000       1
1132.000       1
2037.000       1
Name: weight_kg, Length: 433, dtype: int64

In [1058]:
df["weight_kg"].fillna("-", inplace=True)


In [1059]:
df.groupby(["make_model", "body_type","weight_kg"]).price.describe()

count      mean      std       min  \
make_model     body_type weight_kg                                        
Audi A1        Compact   1010.0      2.000 15450.000  707.107 14950.000   
                         1035.0      6.000 16796.667 2617.867 14390.000   
                         1040.0      2.000 20424.500 2933.786 18350.000   
                         1065.0     36.000 20971.778 1982.554 15500.000   
                         1090.0      9.000 21059.222 2945.233 15998.000   
...                                    ...       ...      ...       ...   
Renault Espace Van       2037.0      1.000 47950.000      NaN 47950.000   
                         2353.0      1.000 22990.000      NaN 22990.000   
                         2410.0      1.000 23990.000      NaN 23990.000   
                         2471.0      5.000 24738.000 8470.639 17400.000   
                         -         377.000 30126.297 7273.476 12614.000   

                                         25%       50%       75%       max  
make_model     body_type weight_kg                                          
Audi A1        Compact   1010.0    15200.000 15450.000 15700.000 15950.000  
                         1035.0    15892.500 15900.000 16575.000 21900.000  
                         1040.0    19387.250 20424.500 21461.750 22499.000  
                         1065.0    18987.500 21690.000 22400.000 23550.000  
                         1090.0    18990.000 22450.000 22800.000 25256.000  
...                                      ...       ...       ...       ...  
Renault Espace Van       2037.0    47950.000 47950.000 47950.000 47950.000  
                         2353.0    22990.000 22990.000 22990.000 22990.000  
                         2410.0    23990.000 23990.000 23990.000 23990.000  
                         2471.0    20900.000 20900.000 25500.000 38990.000  
                         -         24990.000 29990.000 34950.000 68320.000  

[891 rows x 8 columns]

In [1060]:
df["weight_kg"].replace("-", np.nan, inplace=True)

In [1062]:
fill(df, "make_model", "body_type", "weight_kg", "mode")

Number of NaN :  0
------------------
1163.000    1583
1360.000    1419
1487.000     967
1135.000     837
1425.000     744
            ... 
1331.000       1
1132.000       1
1252.000       1
1792.000       1
2037.000       1
Name: weight_kg, Length: 432, dtype: int64


### cons_comb column:

In [1063]:
print('\n''Percentage of Missing Values : %', round(
    df['cons_comb'].isnull().sum()/df.shape[0]*100, 2))
print("Number of Missings           : ",
      df['cons_comb'].isnull().sum())
print("Number of Uniques            : ", df['cons_comb'].nunique())
print('Value counts                 : ''\n''\n',df['cons_comb'].value_counts(dropna=False))


Percentage of Missing Values : % 12.77
Number of Missings           :  2033
Number of Uniques            :  72
Value counts                 : 

 NaN       2033
5.400      770
3.900      733
4.000      713
5.100      657
          ... 
33.000       1
50.000       1
1.000        1
46.000       1
11.000       1
Name: cons_comb, Length: 73, dtype: int64


In [1064]:
cons_comb = (df["cons_country"] + df["cons_city"])/2

In [1065]:
df["cons_comb"] = df["cons_comb"].fillna(cons_comb)

In [1066]:
df["cons_comb"].value_counts(dropna=False)

NaN       1925
5.400      770
3.900      733
4.000      713
5.100      657
          ... 
33.000       1
50.000       1
1.000        1
46.000       1
13.800       1
Name: cons_comb, Length: 79, dtype: int64

In [1067]:
df["cons_comb"].fillna("-", inplace=True)

In [1068]:
df.groupby(["make_model", "body_type","cons_comb"]).price.describe()

count      mean      std       min  \
make_model     body_type cons_comb                                        
Audi A1        Compact   3.0         4.000 14370.250 4481.393 11100.000   
                         3.4         6.000 12755.000  900.750 11800.000   
                         3.5         3.000 14613.000 1848.098 12479.000   
                         3.6         5.000 13960.000 1232.071 12900.000   
                         3.7        50.000 15902.200 2960.324 12900.000   
...                                    ...       ...      ...       ...   
Renault Espace Van       6.8       115.000 34032.313 7847.720 25490.000   
                         7.4        61.000 38163.754 6406.548 28975.000   
                         7.6        14.000 52019.214 7596.268 38990.000   
                         46.0        1.000 25490.000      NaN 25490.000   
                         -         144.000 29865.521 6616.406 12990.000   

                                         25%       50%       75%       max  
make_model     body_type cons_comb                                          
Audi A1        Compact   3.0       11242.500 12840.500 15968.250 20700.000  
                         3.4       11987.500 12640.000 13570.000 13800.000  
                         3.5       14079.500 15680.000 15680.000 15680.000  
                         3.6       12900.000 13900.000 14200.000 15900.000  
                         3.7       13900.000 15040.000 15967.500 23500.000  
...                                      ...       ...       ...       ...  
Renault Espace Van       6.8       28237.500 31990.000 37470.000 58950.000  
                         7.4       33781.000 37475.000 39990.000 54500.000  
                         7.6       48387.500 51350.000 54982.000 64332.000  
                         46.0      25490.000 25490.000 25490.000 25490.000  
                         -         24497.500 29990.000 33525.000 63477.000  

[582 rows x 8 columns]

In [1069]:
df.groupby(["make_model", "age","cons_comb"]).price.describe()

count      mean      std       min       25%  \
make_model     age   cons_comb                                                  
Audi A1        0.000 3.7         3.000 19160.000 1353.034 17900.000 18445.000   
                     3.8         1.000 20000.000      NaN 20000.000 20000.000   
                     4.0        21.000 19382.429 1978.122 16220.000 18000.000   
                     4.2        19.000 19333.632 2981.701 14900.000 16487.500   
                     4.3         6.000 20614.667 1930.760 17999.000 19510.000   
...                                ...       ...      ...       ...       ...   
Renault Espace 3.000 4.7       115.000 22102.078 3195.943 13500.000 19825.000   
                     5.1         1.000 12990.000      NaN 12990.000 12990.000   
                     5.3         6.000 22811.500 3237.385 19000.000 21124.250   
                     6.2        26.000 23683.654 2650.266 17900.000 21950.000   
                     -          42.000 22702.619 3427.571 12990.000 21108.750   

                                     50%       75%       max  
make_model     age   cons_comb                                
Audi A1        0.000 3.7       18990.000 19790.000 20590.000  
                     3.8       20000.000 20000.000 20000.000  
                     4.0       19497.000 20344.000 22919.000  
                     4.2       18775.000 21775.000 25256.000  
                     4.3       20335.000 22232.500 22919.000  
...                                  ...       ...       ...  
Renault Espace 3.000 4.7       21975.000 24900.000 30000.000  
                     5.1       12990.000 12990.000 12990.000  
                     5.3       21695.000 24957.500 27500.000  
                     6.2       23895.000 25980.000 27900.000  
                     -         22990.000 24365.000 32900.000  

[688 rows x 8 columns]

In [1070]:
df.groupby(["body_type","cons_comb"]).price.describe()

count      mean      std       min       25%       50%  \
body_type cons_comb                                                            
Compact   3.0        46.000 12006.826 3959.654  5490.000  8990.000 11022.500   
          3.1         1.000 10900.000      NaN 10900.000 10900.000 10900.000   
          3.2         3.000  9706.000  269.941  9450.000  9565.000  9680.000   
          3.3        59.000  8430.458 1340.129  5890.000  7825.000  7950.000   
          3.4        13.000 12404.538 1993.513  8450.000 10999.000 12400.000   
...                     ...       ...      ...       ...       ...       ...   
Van       6.8       115.000 34032.313 7847.720 25490.000 28237.500 31990.000   
          7.4        61.000 38163.754 6406.548 28975.000 33781.000 37475.000   
          7.6        14.000 52019.214 7596.268 38990.000 48387.500 51350.000   
          46.0        1.000 25490.000      NaN 25490.000 25490.000 25490.000   
          -         150.000 29238.100 7356.305  7900.000 24445.000 29925.000   

                          75%       max  
body_type cons_comb                      
Compact   3.0       14801.500 21400.000  
          3.1       10900.000 10900.000  
          3.2        9834.000  9988.000  
          3.3        8899.500 12990.000  
          3.4       13800.000 15950.000  
...                       ...       ...  
Van       6.8       37470.000 58950.000  
          7.4       39990.000 54500.000  
          7.6       54982.000 64332.000  
          46.0      25490.000 25490.000  
          -         32933.750 63477.000  

[228 rows x 8 columns]

In [1071]:
df["cons_comb"].replace([0.0, 1.0, 1.2, 1.6, 10, 11, 13.8, 32.0, 33.0, 38.0,
                        40.0, 43.0, 46.0, 50.0, 51.0, 54.0, 55.0, "-"], np.nan, inplace=True)


In [1072]:
df["cons_comb"].value_counts(dropna=False)


NaN      1983
5.400     770
3.900     733
4.000     713
5.100     657
         ... 
5.450       2
8.100       2
7.500       1
9.100       1
4.550       1
Name: cons_comb, Length: 62, dtype: int64

In [1073]:
fill(df, "make_model", "body_type", "cons_comb", "median")

Number of NaN :  0
------------------
4.000    1020
5.600     965
5.400     900
5.000     810
4.700     766
         ... 
8.100       2
4.550       2
7.500       1
9.100       1
4.300       1
Name: cons_comb, Length: 63, dtype: int64


I will continue with the cons_comb column, so I no longer need the cons_city and cons_coutry columns.

In [1074]:
df.drop(['cons_city', 'cons_country'], axis=1, inplace=True)


In [1075]:
df.drop(['next_inspection', 'cylinders', 'consumption',
        'co2_emission', 'emission_class'], axis=1, inplace=True)


I think the weight_kg column also has no effect on the price, but for now I'm not dropping it.

In [1076]:
df.columns

Index(['make_model', 'body_type', 'price', 'vat', 'km', 'previous_owners',
       'inspection_new', 'paint_type', 'num_of_doors', 'num_of_seats',
       'gearing_type', 'drive_chain', 'fuel', 'comfort_convenience',
       'entertainment_media', 'extras', 'safety_security', 'gears', 'age',
       'hp_kw', 'type', 'upholstery_type', 'upholstery_color',
       'displacement_cc', 'weight_kg', 'cons_comb'],
      dtype='object')

In [1077]:
df.shape

(15919, 26)

In [1078]:
df.isnull().sum()/df.shape[0]*100


make_model            0.000
body_type             0.000
price                 0.000
vat                   0.000
km                    0.000
previous_owners       0.000
inspection_new        0.000
paint_type            0.000
num_of_doors          0.000
num_of_seats          0.000
gearing_type          0.000
drive_chain           0.000
fuel                  0.000
comfort_convenience   0.000
entertainment_media   0.000
extras                0.000
safety_security       0.000
gears                 0.000
age                   0.000
hp_kw                 0.000
type                  0.000
upholstery_type       0.000
upholstery_color      0.000
displacement_cc       0.000
weight_kg             0.000
cons_comb             0.000
dtype: float64

In [1079]:
df.to_csv("autoscout_filled.csv", index=False)


In [1080]:
df2=pd.read_csv("autoscout_filled.csv")
df2.head()

make_model body_type  price               vat        km  previous_owners  \
0    Audi A1    Sedans  15770    VAT deductible 56013.000            2.000   
1    Audi A1    Sedans  14500  Price negotiable 80000.000            1.000   
2    Audi A1    Sedans  14640    VAT deductible 83450.000            1.000   
3    Audi A1    Sedans  14500    VAT deductible 73000.000            1.000   
4    Audi A1    Sedans  16790    VAT deductible 16200.000            1.000   

   inspection_new paint_type  num_of_doors  num_of_seats  ...  \
0               1   Metallic         5.000         5.000  ...   
1               0   Metallic         3.000         4.000  ...   
2               0   Metallic         4.000         4.000  ...   
3               0   Metallic         3.000         4.000  ...   
4               1   Metallic         5.000         5.000  ...   

                                     safety_security gears   age   hp_kw  \
0  ABS, Central door lock, Daytime running lights... 7.000 3.000  66.000   
1  ABS, Central door lock, Central door lock with... 7.000 2.000 141.000   
2  ABS, Central door lock, Daytime running lights... 7.000 3.000  85.000   
3  ABS, Alarm system, Central door lock with remo... 6.000 3.000  66.000   
4  ABS, Central door lock, Driver-side airbag, El... 7.000 3.000  66.000   

   type upholstery_type upholstery_color  displacement_cc  weight_kg  \
0  Used           Cloth            Black         1422.000   1220.000   
1  Used           Cloth             Grey         1798.000   1255.000   
2  Used           Cloth            Black         1598.000   1135.000   
3  Used           Cloth            Black         1422.000   1195.000   
4  Used           Cloth            Black         1422.000   1135.000   

   cons_comb  
0      3.800  
1      5.600  
2      3.800  
3      3.800  
4      4.100  

[5 rows x 26 columns]

In [1081]:
df2.shape

(15919, 26)